/* PREREQUISITES:
 *	+ Visual Text Analytics license
 *	+ Ensure to run 1_CAS_Initialize.sas first 
 *	+ Ensure that AIRLINES_KEY dataset is loaded into CAS
 *	+ You can generate the following SAS code using the SAS Studio Task: Tasks --> SAS Tasks --> SAS Visual Text Analytics --> Text Parsing and Topic Discovery
 */

/* 
 * 
 * Task code generated by SAS� Studio 5.1
 * 
 * Generated on '7/7/18, 9:47 PM'
 * Generated by 'ssethi'
 * Generated on server 'vta-friday'
 * Generated on SAS platform 'Linux LIN X64 3.10.0-327.10.1.el7.x86_64'
 * Generated on SAS version 'V.03.04M0P070418'
 * Generated on browser 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36'
 * Generated on web client 'https://vta-friday.aatesting.sashq-r.openstack.sas.com/SASStudioV/main?locale=en_US&launchedFromAppSwitcher=true'
 */

ods noproctitle;
libname _tmpcas_ cas caslib="CASUSER";

/* Load default English stop list */
proc casutil;
	load casdata="en_stoplist.sashdat" INCASLIB="referencedata" 
		casout="_stoplist_" outcaslib="CASUSER" replace;
	quit;

proc textmine data=PUBLIC.AIRLINES_KEY;
	var text;
	doc_id key;
	parse entities=std stop=_tmpcas_._stoplist_ outconfig=CASUSER.SVD_CONFIG;
	svd k=25 numlabels=5 outdocpro=CASUSER.SVD_PROJECTIONS 
		outtopics=CASUSER.SVD_TOPICS;
	savestate rstore=CASUSER.SVD_ASTORE;
run;

proc delete data=_tmpcas_._stoplist_;
run;

libname _tmpcas_;