/* PREREQUISITES:
 *	+ Visual Text Analytics license
 *	+ Ensure to run 1_CAS_Initialize.sas first 
 *	+ Ensure that AIRLINES_KEY dataset is loaded into CAS
 *	+ You can generate the following SAS code using the SAS Studio Task: Tasks --> SAS Tasks --> SAS Visual Text Analytics --> Segmentation
 */

/* 
 * 
 * Task code generated by SAS� Studio 5.1
 * 
 * Generated on '7/7/18, 10:49 PM'
 * Generated by 'ssethi'
 * Generated on server 'vta-friday'
 * Generated on SAS platform 'Linux LIN X64 3.10.0-327.10.1.el7.x86_64'
 * Generated on SAS version 'V.03.04M0P070418'
 * Generated on browser 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36'
 * Generated on web client 'https://vta-friday.aatesting.sashq-r.openstack.sas.com/SASStudioV/main?locale=en_US&launchedFromAppSwitcher=true'
 */

ods noproctitle;

proc cas;
	session %sysfunc(getlsessref(PUBLIC));
	action smartData.dataSegment / table={caslib="%sysfunc(getlcaslib(PUBLIC))", 
		name="AIRLINES_KEY"} inputs="text" docId="key" textParse={nounGroups="true", 
		stemming="true"} nSegment=25 maxIters=100 
		docVectOut={caslib="%sysfunc(getlcaslib(CASUSER))", name="_docVectTemp_", 
		replace="true"} termOut={caslib="%sysfunc(getlcaslib(CASUSER))", 
		name="SEGMENT_TERMS", replace="true"};
	run;
quit;

data CASUSER.SEGMENT_RESULTS;
	set CASUSER._docVectTemp_(keep=key _group_);
run;

proc delete data=CASUSER._docVectTemp_;
run;