%tmfilter(	url=http://de.saswiki.org/wiki/KSFE_2016,
			dataset=work.ksfe2016,
			dir=D:\TMP\doc,
			destdir=D:\TMP\txt,
			depth=1,
			language=*German English /*ALL*/,
			force='y',
			/*ext=.pdf .html*/
			numchars=32000);