---
openapi: 3.0.3
info:
  description: An analytics provider implementing the Analytics Gateway - Analytics
    Provider contract must implement these required endpoints.
  version: '3'
  title: Analytics Gateway Provider Required Endpoints
  contact:
    name: SAS Developers
    url: 'https://developer.sas.com'
    email: devex@sas.com
  license:
    name: SAS Institute Inc.
    url: 'https://support.sas.com/techsup/license/index.html'
servers:
- url: 'http://example.com/analyticsGatewayProviderContract'
  description: example.com mock server
tags:
- name: Required
  description: The endpoints that are required to be implemented by an Analytics Gateway
    Provider.
paths:
  /analyticsProviderDetails:
    get:
      tags:
      - Required
      summary: Get the analytics provider details
      description: 'A required endpoint when registering as an analytics provider
        with the CommonAnalytics Platform.  The response provides details about the
        provider and the types of analytics projects the provider will handle. The
        path listed here is suggested, but a provider may implement this endpoint
        using any path.'
      operationId: getAnalyticsProvider
      parameters:
      - name: Content-Type
        in: header
        description: Media type for the collection of resources.
        required: true
        schema:
          type: string
          enum:
          - application/vnd.sas.analytics.provider.details+json
          - application/json
          default: application/vnd.sas.analytics.provider.details+json
      responses:
        '200':
          $ref: '#/components/responses/providerDetails'
components:
  responses:
    providerDetails:
      description: The request succeeded.
      headers:
        Content-Type:
          description: The media type of the response
          schema:
            type: string
            default: application/vnd.sas.analytics.provider.details+json
      content:
        application/vnd.sas.analytics.provider.details+json:
          schema:
            $ref: "#/components/schemas/analyticsProviderDetails"
          examples:
            json:
              $ref: '#/components/examples/providerDetails'
        application/json:
          schema:
            $ref: "#/components/schemas/analyticsProviderDetails"
          examples:
            json:
              $ref: '#/components/examples/providerDetails'
  examples:
    providerDetails:
      description: 'This is an example of a Provider Details.'
      value: ' { "version": 1, "providerName": "Example Analytics Provider", "description":
        "An example provider.", "type": "AACS Example", "providerCapabilities": {
        "PROJECT_CREATE": { "method": "POST", "rel": "create", "href": "/analyticsProvider/projects/create?projectId={projectId}",
        "uri": "/analyticsProvider/projects/create?projectId={projectId}", "type":
        "application/vnd.sas.analytics.project", "responseType": "application/vnd.sas.analytics.project"
        }, "PROJECT_POST_TRANSFER_OUT": { "method": "POST", "rel": "postTransferOut",
        "href": "/analyticsProvider/projects/postTransferOut?projectId={projectId}",
        "uri": "/analyticsProvider/projects/postTransferOut?projectId={projectId}",
        "type": "application/vnd.sas.analytics.transferred.project", "responseType":
        "application/vnd.sas.analytics.transferred.project" }, "PIPELINE_PRE_UPDATE":
        { "method": "POST", "rel": "preUpdate", "href": "/analyticsProvider/pipelines/preUpdate?projectId={projectId}&pipelineId={pipelineId}",
        "uri": "/analyticsProvider/pipelines/preUpdate?projectId={projectId}&pipelineId={pipelineId}",
        "type": "application/vnd.sas.analytics.pipeline", "responseType": "application/vnd.sas.analytics.pipeline"
        }, "PROJECT_POST_UPGRADE_IN_PLACE": { "method": "POST", "rel": "postUpgradeInPlace",
        "href": "/analyticsProvider/projects/postUpgradeInPlace?projectId={projectId}",
        "uri": "/analyticsProvider/projects/postUpgradeInPlace?projectId={projectId}",
        "type": "application/vnd.sas.analytics.upgrade.project", "responseType": "application/vnd.sas.analytics.project"
        }, "COMPONENT_PRE_UPDATE": { "method": "POST", "rel": "preUpdate", "href":
        "/analyticsProvider/components/preUpdate?projectId={projectId}&pipelineId={pipelineId}&componentId={componentId}",
        "uri": "/analyticsProvider/components/preUpdate?projectId={projectId}&pipelineId={pipelineId}&componentId={componentId}",
        "type": "application/vnd.sas.analytics.component", "responseType": "application/vnd.sas.analytics.component"
        }, "PIPELINE_POST_READ": { "method": "POST", "rel": "postRead", "href": "/analyticsProvider/pipelines/postRead?projectId={projectId}&pipelineId={pipelineId}",
        "uri": "/analyticsProvider/pipelines/postRead?projectId={projectId}&pipelineId={pipelineId}",
        "type": "application/vnd.sas.analytics.pipeline", "responseType": "application/vnd.sas.analytics.pipeline"
        }, "PROJECT_COLLECTION_POST_READ": { "method": "POST", "rel": "collectionPostRead",
        "href": "/analyticsProvider/projects/collectionPostRead", "uri": "/analyticsProvider/projects/collectionPostRead",
        "type": "application/vnd.sas.collection", "responseType": "application/vnd.sas.collection",
        "itemType": "application/vnd.sas.analytics.project", "responseItemType": "application/vnd.sas.analytics.project"
        }, "COMPONENT_POST_UPDATE": { "method": "POST", "rel": "postUpdate", "href":
        "/analyticsProvider/components/postUpdate?projectId={projectId}&pipelineId={pipelineId}&componentId={componentId}",
        "uri": "/analyticsProvider/components/postUpdate?projectId={projectId}&pipelineId={pipelineId}&componentId={componentId}",
        "type": "application/vnd.sas.analytics.component", "responseType": "application/vnd.sas.analytics.component"
        }, "PROJECT_POST_READ": { "method": "POST", "rel": "postRead", "href": "/analyticsProvider/projects/postRead?projectId={projectId}",
        "uri": "/analyticsProvider/projects/postRead?projectId={projectId}", "type":
        "application/vnd.sas.analytics.project", "responseType": "application/vnd.sas.analytics.project"
        }, "PROJECT_RELATIONSHIPS_POST_READ": { "method": "GET", "rel": "relationshipsPostRead",
        "href": "/analyticsProvider/projects/relationshipsPostRead?projectId={projectId}",
        "uri": "/analyticsProvider/projects/relationshipsPostRead?projectId={projectId}",
        "type": "application/vnd.sas.collection", "itemType": "application/vnd.sas.relationship"
        }, "PIPELINE_PRE_CREATE": { "method": "POST", "rel": "preCreate", "href":
        "/analyticsProvider/pipelines/preCreate?projectId={projectId}", "uri": "/analyticsProvider/pipelines/preCreate?projectId={projectId}",
        "type": "application/vnd.sas.analytics.pipeline", "responseType": "application/vnd.sas.analytics.pipeline"
        }, "PROJECT_PRE_CREATE": { "method": "POST", "rel": "preCreate", "href": "/analyticsProvider/projects/preCreate",
        "uri": "/analyticsProvider/projects/preCreate", "type": "application/vnd.sas.analytics.project",
        "responseType": "application/vnd.sas.analytics.project" }, "COMPONENT_POST_READ":
        { "method": "POST", "rel": "postRead", "href": "/analyticsProvider/components/postRead?projectId={projectId}&pipelineId={pipelineId}&componentId={componentId}",
        "uri": "/analyticsProvider/components/postRead?projectId={projectId}&pipelineId={pipelineId}&componentId={componentId}",
        "type": "application/vnd.sas.analytics.component", "responseType": "application/vnd.sas.analytics.component"
        }, "PIPELINE_POST_UPDATE": { "method": "POST", "rel": "postUpdate", "href":
        "/analyticsProvider/pipelines/postUpdate?projectId={projectId}&pipelineId={pipelineId}",
        "uri": "/analyticsProvider/pipelines/postUpdate?projectId={projectId}&pipelineId={pipelineId}",
        "type": "application/vnd.sas.analytics.pipeline", "responseType": "application/vnd.sas.analytics.pipeline"
        }, "PIPELINE_PRE_DELETE": { "method": "POST", "rel": "preDelete", "href":
        "/analyticsProvider/pipelines/preDelete?projectId={projectId}&pipelineId={pipelineId}",
        "uri": "/analyticsProvider/pipelines/preDelete?projectId={projectId}&pipelineId={pipelineId}"
        }, "PIPELINE_RESOURCE_SUMMARY_POST_READ": { "method": "POST", "rel": "resourceSummaryPostRead",
        "href": "/analyticsProvider/pipelines/resourceSummaryPostRead?projectId={projectId}&pipelineId={pipelineId}",
        "uri": "/analyticsProvider/pipelines/resourceSummaryPostRead?projectId={projectId}&pipelineId={pipelineId}",
        "type": "application/vnd.sas.summary", "responseType": "application/vnd.sas.summary"
        }, "PIPELINE_PRE_PATCH": { "method": "POST", "rel": "prePatch", "href": "/analyticsProvider/pipelines/prePatch?projectId={projectId}&pipelineId={pipelineId}",
        "uri": "/analyticsProvider/pipelines/prePatch?projectId={projectId}&pipelineId={pipelineId}",
        "type": "application/json-patch", "responseType": "application/json-patch"
        }, "PROJECT_POST_TRANSFER_IN": { "method": "POST", "rel": "postTransferIn",
        "href": "/analyticsProvider/projects/postTransferIn?projectId={projectId}",
        "uri": "/analyticsProvider/projects/postTransferIn?projectId={projectId}",
        "type": "application/vnd.sas.analytics.transferred.project", "responseType":
        "application/vnd.sas.analytics.transferred.project" }, "PROJECT_PRE_DELETE":
        { "method": "POST", "rel": "preDelete", "href": "/analyticsProvider/projects/preDelete?projectId={projectId}",
        "uri": "/analyticsProvider/projects/preDelete?projectId={projectId}" }, "PIPELINE_POST_CREATE":
        { "method": "POST", "rel": "postCreate", "href": "/analyticsProvider/pipelines/postCreate?projectId={projectId}&pipelineId={pipelineId}",
        "uri": "/analyticsProvider/pipelines/postCreate?projectId={projectId}&pipelineId={pipelineId}",
        "type": "application/vnd.sas.analytics.pipeline", "responseType": "application/vnd.sas.analytics.pipeline"
        }, "PROJECT_UPDATE": { "method": "POST", "rel": "update", "href": "/analyticsProvider/projects/update?projectId={projectId}",
        "uri": "/analyticsProvider/projects/update?projectId={projectId}", "type":
        "application/vnd.sas.analytics.project", "responseType": "application/vnd.sas.analytics.project"
        }, "PIPELINE_COLLECTION_POST_READ": { "method": "POST", "rel": "collectionPostRead",
        "href": "/analyticsProvider/pipelines/collectionPostRead?projectId={projectId}",
        "uri": "/analyticsProvider/pipelines/collectionPostRead?projectId={projectId}",
        "type": "application/vnd.sas.collection", "responseType": "application/vnd.sas.collection",
        "itemType": "application/vnd.sas.summary", "responseItemType": "application/vnd.sas.summary"
        }, "COMPONENT_PRE_DELETE": { "method": "POST", "rel": "preDelete", "href":
        "/analyticsProvider/components/preDelete?projectId={projectId}&pipelineId={pipelineId}&componentId={componentId}",
        "uri": "/analyticsProvider/components/preDelete?projectId={projectId}&pipelineId={pipelineId}&componentId={componentId}"
        } }, "enumerationGroups": [ { "id": "templateGroups", "items": [ { "id": "example",
        "name": "AACS Example" } ], "enumerationGroupItemsAsMap": { "Example": { "id":
        "example", "name": "AACS Example" } } } ], "productIds": [] }'
  schemas:
    analyticsProviderDetails:
      title: Analytics Provider Details
      description: Details about an analytics provider.  These details are used to
        describe the provider and specify how the Analytics Gateway and its clients
        can interact with the provider.
      x-sas-media-type:
        name: vnd.sas.analytics.provider.details
        version: 1
      properties:
        providerName:
          type: string
          description: The localized name of the provider.  This is only for informational
            purposes.
        description:
          type: string
          description: A brief, localized description of the provider.  This is optional,
            and only used for informational purposes.
        enumerationGroups:
          type: array
          description: The list of provider enumeration groups.  This provides the
            list of valid values and localized display names for the properties of
            provider-specific resources.  An enumeration group can be used by an Analytics
            Gateway client to populate a provider-specific menu, for example.
          items:
            $ref: "#/components/schemas/enumerationGroup"
        productIds:
          type: array
          description: 'List of licensed product ids associated with the provider.
            Each id must have an existing, unexpired license in order for the provider
            to be made available to gateway clients.'
          items:
            type: integer
            format: int32
        providedLinks:
          type: object
          description: Map that indicates provider links that should be added to various
            media types.
          additionalProperties:
            type: object
        providerCapabilities:
          type: object
          description: Map that indicates the capabilities this provider supports.
          additionalProperties:
            type: object
        toolboxItems:
          type: array
          description: List of links to provider toolbox items.  Toolbox items include
            provider-specific component templates, pipeline templates, and validation
            models.
          items:
            $ref: "#/components/schemas/link"
        type:
          type: string
          description: Localized string that describes the project type handled by
            the provider.
        version:
          type: integer
          format: int32
          description: "The API representation version."
    enumerationGroup:
      title: Enumeration Group
      description: An advanced analytics enumeration group that contains a list of
        enumeration group items.
      x-sas-media-type:
        name: vnd.sas.analytics.enumeration.group
        version: 1
      properties:
        id:
          type: string
          description: The group id.
        items:
          type: array
          description: The enumeration group items defined for this group.
          items:
            $ref: "#/components/schemas/enumerationGroupItem"
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
    enumerationGroupItem:
      title: Enumeration Group Item
      description: Represents an advanced analytics enumeration item
      properties:
        id:
          type: string
          description: The enumeration item id
        name:
          type: string
          description: The enumeration item name. It is localized based on the user
            locale.
