---
openapi: 3.0.3
info:
  version: "1"
  title: Advanced Analytics Execution
  description: The Advanced Analytics Execution API is used to manage the execution
    of analytics pipelines. The initial implementation of this API includes just the
    required REST endpoints to satisfy the Job Execution Provider contract for the
    "NO-OP" provider.
  contact:
    name: SAS Developers
    url: "https://developer.sas.com"
    email: devex@sas.com
  license:
    name: SAS Institute Inc.
    url: "https://support.sas.com/techsup/license/index.html"
servers:
- url: "http://example.com/analyticsExecution"
  description: mock server
tags:
- name: Root
  description: The operations for the root resource.
paths:
  /:
    get:
      tags:
      - Root
      summary: Get the API object
      description: The API object contains a set of links for the supported endpoints.
      operationId: root
      responses:
        "200":
          description: OK
          headers: {}
          content:
            "application/vnd.sas.api+json":
              schema:
                $ref: "#/components/schemas/api"
              examples:
                "root":
                  $ref: "#/components/examples/rootResponse200"
            "application/json":
              schema:
                $ref: "#/components/schemas/api"
              examples:
                "root":
                  $ref: "#/components/examples/rootResponse200"
components:
  schemas:
    link:
      description: A Link is the SAS implementation of an hateoas link.
      type: object
      properties:
        method:
          type: string
          xml:
            attribute: true
        rel:
          type: string
          xml:
            attribute: true
        href:
          type: string
          xml:
            attribute: true
        uri:
          type: string
          xml:
            attribute: true
        type:
          type: string
          xml:
            attribute: true
        responseType:
          type: string
          xml:
            attribute: true
        itemType:
          type: string
          xml:
            attribute: true
        responseItemType:
          type: string
          xml:
            attribute: true
        title:
          type: string
          xml:
            attribute: true
      xml:
        name: Link
    api:
      description: This lists the primary API entry points for users. It does not
        include any system endpoints that are required for inclusion in a SAS Viya
        deployment, but not intended for end-users. It also does not include any common
        endpoints that may be provided by the framework in which the service was implemented.
      type: object
      properties:
        version:
          type: integer
          format: int32
          xml:
            attribute: true
        links:
          type: array
          xml:
            wrapped: true
          items:
            $ref: "#/components/schemas/link"
      xml:
        name: resources
  examples:
    rootResponse200:
      summary: API Root Response
      description: When issuing a GET on the root of the API, the primary user entry-points
        are returned as a collection of links.
      value:
        version: 1
        links:
        - method: GET
          rel: self
          href: /analyticsExecution
          uri: /analyticsExecution
          type: application/vnd.sas.api+json;version=1;charset=UTF-8
