---
openapi: 3.0.3
info:
  title: Sample Application Programming Interface
  version: "1"
  description: 'This is a sample api specification for testing purpose'
  contact:
    name: SAS Developers
    url: https://developer.sas.com
    email: devex@sas.com
servers:
- description: "hostname for mock server"
  url: "http://example.com/apidemo"
paths:
  '/':
    get:
      summary: Return the root
      responses:
        '200':
          description: root
          headers:
            Content-Type:
              schema:
                type: string
          content:
            application/vnd.sas.api+json:
              schema:
                type: string
              example: root
            application/json:
              schema:
                type: string
              example: root
      description: Returns root.
      operationId: root
      tags:
      - Root
  '/people/{peopleId}':
    get:
      summary: Returns a user by ID
      parameters:
      - name: peopleId
        in: path
        required: true
        description: The ID of the user to return.
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: A user object.
          headers:
            Content-Type:
              schema:
                type: integer
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                example-1:
                  value:
                    id: 1
                    name: Steve Smith
                example-3:
                  value:
                    id: 3
                    name: Bo Beauson
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                example-1:
                  value:
                    id: 1
                    name: Steve Smith
                example-3:
                  value:
                    id: 3
                    name: Bo Beauson
        '400':
          description: The specified user ID is invalid (not a number).
          content:
            'application/vnd.sas.error+json':
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
            'application/json':
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
        '404':
          description: A user with the specified ID was not found.
          content:
            'application/vnd.sas.error+json':
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
            'application/json':
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
      description: Returns one person.
      operationId: getOnePerson
      tags:
      - People
    head:
      summary: Check availability of user by ID
      parameters:
      - name: peopleId
        in: path
        required: true
        description: The ID of the user to return.
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: Success. The user is returned.
          headers:
            Content-Type:
              schema:
                type: integer
        '400':
          description: Invalid. The specified user ID is invalid (not a number).
          headers:
            Content-Type:
              schema:
                type: integer
        '404':
          description: Not Found. A user with the specified ID was not found.
          headers:
            Content-Type:
              schema:
                type: integer
      description: Retrieve the headers and check the availability of a user by ID
      operationId: headersForOnePerson
      tags:
      - People
    post:
      summary: 'Add a person to the server'
      operationId: createPerson
      parameters:
      - name: peopleId
        in: path
        required: true
        description: The ID of the user to return.
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: success
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                example-1:
                  value:
                    id: 1
                    name: Steve Smith
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                example-1:
                  value:
                    id: 1
                    name: Steve Smith
        '201':
          description: Specified user ID created successfully.
          headers:
            Location:
              description: The URI of the newly created user.
              schema:
                type: string
        '400':
          description: Invalid. The specified user ID is invalid (not a number).
      requestBody:
        content:
          application/vnd.sas.api+json:
            schema:
              $ref: '#/components/schemas/user'
            examples:
              example-1:
                value:
                  id: 1
                  name: Steve Smith
          application/json:
            schema:
              $ref: '#/components/schemas/user'
            examples:
              example-1:
                value:
                  id: 1
                  name: Steve Smith
            encoding:
              id:
                contentType: integer
              name:
                contentType: string
        description: "Give id and name of person you'd like to create."
      description: Creates new Person.
      tags:
      - People
    put:
      parameters:
      - name: peopleId
        in: path
        required: true
        description: The ID of the user to return.
        schema:
          type: integer
          format: int64
          minimum: 1
      - name: If-Match
        in: header
        description: when this is an update to an entry, then this field needs to
          be present
        schema:
          type: string
          pattern: "[0-9]*"
      summary: 'Update a persons information in the server'
      operationId: updatePerson
      responses:
        '200':
          description: OK
          headers:
            ETag:
              description: An tag that identifies this revision of this person.
              schema:
                type: string
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: '#/components/schemas/user'
              example:
                id: 1
                name: Steve Smith
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              example:
                id: 1
                name: Steve Smith
        '400':
          description: "Bad Request. The request is not porperly formed."
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
        '412':
          description: "Unable to complete request. Precondition failed"
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
        '428':
          description: "Unable to complete request. Precondition is required"
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
      requestBody:
        content:
          application/vnd.sas.api+json:
            schema:
              $ref: '#/components/schemas/user'
            examples:
              example-3:
                $ref: '#/components/examples/exam-3'
          application/json:
            schema:
              $ref: '#/components/schemas/user'
            examples:
              example-3:
                $ref: '#/components/examples/exam-3'
        description: "Give id and name of person you'd like to create."
      description: Updates existing person.
      tags:
      - People
    delete:
      summary: 'Remove a person from the server'
      operationId: deletePerson
      parameters:
      - name: peopleId
        in: path
        required: true
        description: The ID of the user to return.
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        '202':
          description: OK
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                example-1:
                  $ref: '#/components/examples/example-1'
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                example-1:
                  $ref: '#/components/examples/example-1'
        '204':
          description: OK
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                example-1:
                  $ref: "#/components/examples/example-1"
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                example-1:
                  $ref: "#/components/examples/example-1"
      description: Deletes exisitng person.
      tags:
      - People
  '/people':
    get:
      summary: All People Created
      tags:
      - People
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/vnd.sas.api+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
              examples:
                example-2:
                  value:
                  - id: 1
                    name: Steve Smith
                  - id: 2
                    name: John Jacob Jinglehimmer Smith
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
              examples:
                example-2:
                  value:
                  - id: 1
                    name: Steve Smith
                  - id: 2
                    name: John Jacob Jinglehimmer Smith
      operationId: getPeople
      description: Returns all the people in the server.
components:
  schemas:
    user:
      title: User
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
      description: A single user.
    errorResponse:
      title: error
      description: The representaiton of an error/
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The error message.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
  examples:
    exam-3:
      summary: This is a user object.
      description: This is a description pertaining to this object.
      value:
        id: 3
        name: Bo Beauson
    example-1:
      description: Sample user object
      value:
        id: 1
        name: Steve Smith
    badRequestErrorResponse:
      summary: Bad request error responses
      description: bad request error response for a PUT request.
      value:
        message: The user ID was not valid.
        version: 2
        httpStatusCode: 400
tags:
- name: People
  description: Everything about the person.
  externalDocs:
    description: Find out more
    url: 'http://swagger.io'
- name: Root
  description: Api root.
