---
openapi: 3.0.3
info:
  title: BOSS
  description: |
    The BOSS API provides endpoints that determine the liveness and readiness status for Business Orchestration Services.
    The liveness endpoint indicates whether the BOSS pod is running.
    The readiness endpoint indicates whether the BOSS pod is ready to respond to requests.
  version: "1"
  contact:
    name: SAS Developers
    url: "https://developer.sas.com"
    email: devex@sas.com
  termsOfService: "https://www.sas.com/en_us/legal/copyright.html"
servers:
- url: "https://example.com/boss"
  description: This is an example of a base URL.
tags:
- name: Internal
  description: Contains the operations for internal API calls.
- name: Root
  description: Contains the operations for the root API.
paths:
  /:
    get:
      tags:
      - Root
      summary: Return a list of top-level links
      description: >
        Returns the links to the top-level resources for the API.
      operationId: root
      responses:
        "200":
          description: The request was successful.
          headers:
            Content-Type:
              $ref: "#/components/headers/contentTypeResponseHeader"
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                API:
                  $ref: "#/components/examples/root"
            application/json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                API:
                  $ref: "#/components/examples/root"
        "404":
          description: The API is unavailable.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                Error - API Unavailable:
                  $ref: "#/components/examples/404NotAvailable"
  /internal/live:
    get:
      summary: Check if the BOSS service is live
      operationId: getLive
      tags:
      - Internal
      description: |
        Returns "UP" if the BOSS container is alive.
        If the request fails, a null value is returned. There are no error codes associated with this endpoint.
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                enum:
                - application/json
          content:
            application/vnd.sas.api+json:
              schema:
                type: string
              examples:
                default:
                  $ref: "#/components/examples/live"
            application/json:
              schema:
                type: string
              examples:
                default:
                  $ref: "#/components/examples/live"
  /internal/ready:
    get:
      summary: Check if BOSS routes are ready
      operationId: getReady
      tags:
      - Internal
      description: |
        Returns "UP" if the loaded routes in BOSS are ready to be executed.
        If the request fails, a null value is returned. There are no error codes associated with this endpoint.
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                enum:
                - application/json
          content:
            application/vnd.sas.api+json:
              schema:
                type: string
              examples:
                default:
                  $ref: "#/components/examples/ready"
            application/json:
              schema:
                type: string
              examples:
                default:
                  $ref: "#/components/examples/ready"
components:
  headers:
    contentTypeResponseHeader:
      description: The media type of the response body.
      schema:
        type: string
  schemas:
    error2:
      title: Error
      type: object
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: "#/components/schemas/error2"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
        links:
          description: The API's top-level links.
          type: array
          items:
            $ref: "#/components/schemas/link"
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
  examples:
    live:
      description: Response example for /internal/live
      value: UP
    404NotAvailable:
      summary: Error - API Unavailable
      description: The API is unavailable.
      value:
        version: 1
        httpStatusCode: 404
        message: Not Found
        details: The service is unavailable.
    ready:
      description: Response example for /internal/ready
      value: UP
    root:
      summary: Root API Response
      description: The root response consists of a collection of links that can be
        used to navigate the API.
      value:
        version: 1
        links:
        - method: GET
          rel: root
          href: /
          uri: /
          type: application/vnd.sas.api+json
          itemType: application/vnd.sas.internal
        - method: GET
          rel: live
          href: /boss/internal/live
          uri: /boss/internal/live
          type: application/vnd.sas.api+json
          itemType: application/vnd.sas.internal
        - method: GET
          rel: ready
          href: /boss/internal/ready
          uri: /boss/internal/ready
          type: application/vnd.sas.api+json
          itemType: application/vnd.sas.internal
