---
openapi: 3.0.3
info:
  title: CAS Proxy
  contact:
    name: SAS Developers
    url: "https://developer.sas.com"
    email: devex@sas.com
  description: >
    ### Overview


    The CAS Proxy API provides a <I>gateway</I> to a specific CAS REST server.

    This API exists to allow REST requests to be directed to a specific CAS server
    using the CAS server name

    as part of the request URI.<p>


    ### Headers, Body, and Query Parameters


    #### Headers


    All headers from the original request are copied directly to the request being
    made to the CAS REST server.


    #### Body


    The body from the original request is copied directly to the request being made
    to the CAS REST server.


    #### Query Parameters


    All query parameters submitted are passed on to the CAS REST server.



    ### Examples


    A few examples follow.


    #### Controller Information


    http://{roothost}/casProxy/servers/{serverName}/cas


    ```{

    "type": "Controller",

    "state": "Running",

    "client": 45781,

    "control": 65486,

    "process": {
      "id": "133386",
      "owner": "userId",
      "uptime": 219.25,
      "userCPU": 0.13,
      "sysCPU": 0.29,
      "memoryUsed": 7131136,
      "maxMemoryUsed": 7131136,
      "threadCount": 17,
      "maxThreadCount": 17,
      "ioCount": 16,
      "os": {
        "name": "Linux",
        "version": "#1 SMP Wed Jul 1 18:23:37 EDT 2015",
        "release": "2.6.32-573.el6.x86_64"
      },
      "system": {
        "type": "",
        "name": "X86_64 Linux"
      },
      "casVersion": {
        "version": "V.03.00M0D04242016",
        "buildDate": "Apr 24 2016",
        "buildTime": "18:54:54"
      }
    }

    ```}


    #### List Nodes


    http://{roothost}/casProxy/servers/{serverName}/cas/nodes


    ```[
      {
        "name": "somegrid001.example.com",
        "port": 65486,
        "type": "Controller",
        "connected": true,
        "pid": 133386,
        "httpPort": 25781,
        "httpProtocol": "http",
        "uuid": "10D60B1E-6E76-3142-AD10-9C6239A4C40C"
      },
      {
        "name": "somegrid002.example.com",
        "port": 0,
        "type": "Worker",
        "connected": true,
        "pid": 56990,
        "httpPort": 38526,
        "httpProtocol": "http",
        "uuid": "B8177CF5-5302-7A4C-BCAD-BA2D4981BFAA"
      },
      {
        "name": "somegrid003.example.com",
        "port": 0,
        "type": "Worker",
        "connected": true,
        "pid": 39079,
        "httpPort": 44061,
        "httpProtocol": "http",
        "uuid": "885DC677-3468-C240-A057-EDDE4077E80C"
      },
    ```]



    #### Table Information
  version: "1"
externalDocs:
  description: >
    Documentation for the CAS REST API called by this API can be found
    at http://developer.sas.com.
  url: http://developer.sas.com
paths:
  /:
    get:
      summary: API Root Resource
      description: API information
      operationId: root
      tags:
      - Root
      responses:
        "200":
          description: Version information about the API.
        "401":
          description: Not authenticated
  "/servers/{serverName}/{passThroughUrl}":
    get:
      operationId: General
      summary: Make CAS REST call passing the GET http verb
      description: Makes REST call to CAS server name specified
      tags:
      - General
      parameters:
      - description: The name of the server.
        in: path
        name: serverName
        required: true
        schema:
          type: string
      - name: passThroughUrl
        in: path
        required: true
        description: The portion of the URL that is passed directly to the CAS Server
          REST API. See CAS Server REST API documentation for available functionality.
        schema:
          type: string
      responses:
        "200":
          description: >
            See CAS Server REST API documentation for responses. NOTE -
            Responses returned by this service generally are from connections
            made to the CAS Server REST API. See CAS Server REST API
            documentation for available functionality.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden - the user does not have permission to complete this
            request.
        "404":
          description: Not Found - the requested server name does not exist.
    post:
      summary: Make CAS REST call passing the POST http verb
      description: Makes REST call to CAS server name specified
      operationId: passPost
      tags:
      - General
      parameters:
      - description: The name of the server.
        in: path
        name: serverName
        required: true
        schema:
          type: string
      - name: passThroughUrl
        in: path
        required: true
        description: The portion of the URL that is passed directly to the CAS Server
          REST API. See CAS Server REST API documentation for available functionality.
        schema:
          type: string
      requestBody:
        $ref: "#/components/requestBodies/JSONString"
      responses:
        "200":
          description: >
            See CAS Server REST API documentation for responses. NOTE -
            Responses returned by this service generally are from connections
            made to the CAS Server REST API. See CAS Server REST API
            documentation for available functionality.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden - the user does not have permission to complete this
            request.
        "404":
          description: Not Found - the requested server name does not exist.
    put:
      summary: Make CAS REST call passing the PUT http verb
      description: Makes REST call to CAS server name specified
      operationId: passPut
      tags:
      - General
      parameters:
      - description: The name of the server.
        in: path
        name: serverName
        required: true
        schema:
          type: string
      - name: passThroughUrl
        in: path
        required: true
        description: The portion of the URL that is passed directly to the CAS Server
          REST API. See CAS Server REST API documentation for available functionality.
        schema:
          type: string
      requestBody:
        $ref: "#/components/requestBodies/JSONString"
      responses:
        "200":
          description: >
            See CAS Server REST API documentation for responses. NOTE -
            Responses returned by this service generally are from connections
            made to the CAS Server REST API. See CAS Server REST API
            documentation for available functionality.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden - the user does not have permission to complete this
            request.
        "404":
          description: Not Found - the requested server name does not exist.
    delete:
      summary: Make CAS REST call passing the DELETE http verb
      description: Makes REST call to CAS server name specified
      operationId: passDelete
      tags:
      - General
      parameters:
      - description: The name of the server.
        in: path
        name: serverName
        required: true
        schema:
          type: string
      - name: passThroughUrl
        in: path
        required: true
        description: The portion of the URL that is passed directly to the CAS Server
          REST API. See CAS Server REST API documentation for available functionality.
        schema:
          type: string
      responses:
        "200":
          description: >
            See CAS Server REST API documentation for responses. NOTE -
            Responses returned by this service generally are from connections
            made to the CAS Server REST API. See CAS Server REST API
            documentation for available functionality.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden - the user does not have permission to complete this
            request.
        "404":
          description: Not Found - the requested server name does not exist.
tags:
- name: Root
  description: Root paths.
- name: General
  description: General paths.
servers:
- url: http://example.com/casProxy
  description: This is an example base URL.
components:
  requestBodies:
    JSONString:
      description: >
        Request body with type JSONString.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/JSONString"
  schemas:
    JSONString:
      type: string
      description: >
        JSON request body to pass to the CAS Server REST API (for POST/PUT
        requests). See CAS REST API documentation for available functionality.
