---
openapi: 3.0.3
info:
  version: "1"
  title: Catalog Metadata Contract
  description: >
    The catalog metadata contract documents the API that providers need
    to implement for object metadata retrieval.  This API contract provides a
    common set of endpoints for retrieval of the metadata instances for a
    metadata object type. <p>The primary implementation of this contract is for
    a `GET` on `/{provider}/commons/catalog/{typeNamePlural}/{instanceId}` to
    get an metadata archive.  This archive contains detailed metadata
    information about the object and its relationships.
  termsOfService: "https://www.sas.com/en_us/legal/copyright.html"
  contact:
    name: SAS Developers
    email: devex@sas.com
    url: "https://developer.sas.com"
servers:
- url: "http://example.com/catalogMetadataContract"
  description: The Catalog Metadata provider server.
tags:
- name: Metadata Contract
  description: The Metadata Contract.
paths:
  "/commons/catalog/{typeNamePlural}/{instanceId}":
    head:
      tags:
      - Metadata Contract
      summary: Get the headers for a metadata archive with collections of metadata
        entities, relationships, and classifications
      operationId: headersForMetadataArchive
      description: Returns the headers for a collection of entities, relationships,
        and classifications related to the given resource.
      parameters:
      - name: typeNamePlural
        required: true
        description: The plural form of the name of the type definition whose instance
          data is being retrieved.
        in: path
        schema:
          type: string
      - name: instanceId
        required: true
        description: The identifier of the instance being retrieved.
        in: path
        schema:
          type: string
      responses:
        "200":
          description: The request succeeded.
          headers:
            Content-Type:
              description: The media type of the response body.
              schema:
                type: string
        "404":
          description: The specified resource was not found.
    get:
      tags:
      - Metadata Contract
      summary: Get a metadata archive with collections of metadata entities, relationships,
        and classifications
      operationId: getMetadataArchive
      description: Returns a collection of entities, relationships, classifications
        related to the given resource.
      parameters:
      - name: typeNamePlural
        required: true
        description: The plural form of the name of the type definition whose instance
          data is being retrieved.
        in: path
        schema:
          type: string
      - name: instanceId
        required: true
        description: The identifier of the instance being retrieved.
        in: path
        schema:
          type: string
      responses:
        "200":
          description: The request succeeded.
          headers:
            Content-Type:
              description: The media type of the response body.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/metadataArchive"
              examples:
                Metadata Archive:
                  $ref: "#/components/examples/metadataArchiveResponse"
            application/vnd.sas.metadata.archive+json:
              schema:
                $ref: "#/components/schemas/metadataArchive"
              examples:
                Metadata Archive:
                  $ref: "#/components/examples/metadataArchiveResponse"
        "404":
          description: The specified resource was not found.
          content:
            "application/vnd.sas.error+json":
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                Error - Not Found:
                  summary: Error - Not Found
                  description: The specified resource was not found.
                  value:
                    version: 2
                    httpStatusCode: 404
                    message: Not Found
                    details: No object was found with the ID "5cdc24ec-11ad-45ab-839d-710bd0668d93".
components:
  schemas:
    metadataSummary:
      title: Metadata Summary
      type: object
      description: The basic metadata properties present on all objects.
      required:
      - type
      properties:
        createdBy:
          type: string
          description: The identity that created this object. The value is ignored
            on input.
          readOnly: true
        creationTimeStamp:
          type: string
          description: The date and time this object was created, in the format of
            YYYY-MM-DDThh:mm:ss.sssZ. The value is ignored on input.
          format: date-time
          readOnly: true
        description:
          type: string
          description: The user description of this instance of metadata; the maximum
            length is 1000.
        label:
          type: string
          description: The user-facing name of this object; the maximum length is
            100. Sometimes called the business label.
        modifiedBy:
          type: string
          description: the identity that modified this object last. The value is ignored
            on input.
          readOnly: true
        modifiedTimeStamp:
          type: string
          description: The date and time this object was last modified, in the format
            of YYYY-MM-DDThh:mm:ss.sssZ. The value is ignored on input.
          format: date-time
          readOnly: true
        name:
          type: string
          description: The system name of this object; the maximum length is 100.
        type:
          type: string
          description: The type of resource this metadata represents.  Usually the
            "name" of the type registered in the types API for this object instance.
        version:
          type: integer
          description: The version of the media type. The value is ignored on input.
          readOnly: true
    anchor:
      title: anchor object for this archive
      type: object
      description: The object that owns the lifecycle and manages entities and classifications
        defined in this archive.
      properties:
        uri:
          type: string
          description: The URI of the service object that manages this archive.
        instanceId:
          type: string
          description: The catalog id of the service object that manages this archive.
    instance:
      title: Metadata Instance
      type: object
      description: The basic metadata properties present on all instances with pointer
        to definition.
      allOf:
      - $ref: "#/components/schemas/metadataSummary"
      - type: object
        properties:
          anchor:
            $ref: "#/components/schemas/anchor"
          definitionId:
            type: string
            description: The catalog definition id for this instance of an entity,
              relationship, or classification.
          instanceId:
            type: string
            description: The catalog instance id for this instance of an entity, relationship,
              or classification.
          attributes:
            type: object
            description: The attributes represented as keys with values; the maximum
              length of the key is 100 and the maximum length of the value is 1000.
            additionalProperties: true
    entity:
      title: Entity Instance
      type: object
      description: The entity object in metadata with a resourceId to describe the
        source of metadata.
      allOf:
      - $ref: "#/components/schemas/instance"
      - type: object
        required:
        - uri
        properties:
          uri:
            type: string
            description: The URI of the resource that this instance represents.
          classifications:
            type: array
            description: The classifications to apply to this entity.
            items:
              type: string
              description: The classification by name to apply to this entity.
    relationship:
      title: Relationship Instance
      type: object
      description: The instance of a relationship definition which relates two entities.
      allOf:
      - $ref: "#/components/schemas/instance"
      - type: object
        required:
        - endpoint1Uri
        - endpoint2Uri
        properties:
          endpoint1Id:
            type: string
            description: The catalog instance identity for the endpoint.
          endpoint1Uri:
            type: string
            description: The URI of the first entity endpoint.  The value is ignored
              on input.
          endpoint2Id:
            type: string
            description: The catalog instance identity for the endpoint.
          endpoint2Uri:
            type: string
            description: The URI of the second entity endpoint.  The value is ignored
              on input.
    classification:
      title: Classification Instance
      type: object
      description: The classification in metadata used to categorize entities.
      allOf:
      - $ref: "#/components/schemas/instance"
      - type: object
        properties:
          entities:
            type: array
            description: The entities to apply this classification. This is used where
              this is a new classification instance for entities.
            items:
              type: string
              description: The entity uri for any entity to apply this classification
                to.
    metadataArchive:
      title: Metadata Archive
      type: object
      description: Collection of metadata objects, separated by catalog instance type.
      properties:
        anchor:
          $ref: "#/components/schemas/anchor"
        classifications:
          type: array
          description: An array that contains classification instances or errors resulting
            from creating or updating those instances.
          items:
            $ref: "#/components/schemas/classification"
        entities:
          type: array
          description: An array that contains entity instances or errors resulting
            from creating or updating those instances.
          items:
            $ref: "#/components/schemas/entity"
        relationships:
          type: array
          description: An array that contains relationship instances or errors resulting
            from creating or updating those instances.
          items:
            $ref: "#/components/schemas/relationship"
        version:
          type: integer
          description: The version of the media type.
          readOnly: true
    error2:
      title: Error
      type: object
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: "#/components/schemas/error2"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
  examples:
    metadataArchiveResponse:
      summary: Metadata Archive
      description: An archive containing metadata for the specified object.
      value:
        anchor:
          uri: /dataFlows/dataFlows/73515871-f990-4b05-a034-322751ca9428
        entities:
        - creationTimeStamp: 2022-12-02T09:09:52.866000Z
          modifiedTimeStamp: 2022-12-02T09:09:52.866000Z
          anchor:
            uri: /dataTables/dataSources/Compute~fs~57145902-e8dc-4c87-8295-31b291838831~fs~SASHELP/tables/BASEBALL
          name: BASEBALL
          label: 1986 Baseball Data
          type: sasTable
          uri: /dataTables/dataSources/Compute~fs~57145902-e8dc-4c87-8295-31b291838831~fs~SASHELP/tables/BASEBALL
        - creationTimeStamp: 2022-12-02T09:09:52.876000Z
          modifiedTimeStamp: 2022-12-02T09:09:52.876000Z
          attributes:
            creator: sasboot
            dateCreated: 2022-12-02T09:09:52.876000Z
            dateModified: 2022-12-02T09:09:52.876000Z
            editor: sasboot
            stepCount: 3
          instanceId: 73515871-f990-4b05-a034-322751ca9428
          name: BaseballFilteredFlow_FedContent.flw
          label: BaseballFilteredFlow_FedContent.flw
          type: dataFlow
          version: 1
          uri: /dataFlows/dataFlows/73515871-f990-4b05-a034-322751ca9428
        relationships:
        - creationTimeStamp: 2022-12-02T09:09:52.882000Z
          modifiedTimeStamp: 2022-12-02T09:09:52.882000Z
          type: processAssets
          version: 1
          endpoint1Uri: /dataFlows/dataFlows/73515871-f990-4b05-a034-322751ca9428
          endpoint2Uri: /dataTables/dataSources/Compute~fs~57145902-e8dc-4c87-8295-31b291838831~fs~SASHELP/tables/BASEBALL
        version: 1
