---
openapi: 3.0.3
info:
  version: "1"
  title: SAS Config Reconciler
  contact:
    name: SAS Developers
    url: https://developer.sas.com
    email: devex@sas.com
  description: This API will rollout updates based on configuration changes.
servers:
- url: http://example.com/configReconciler
  description: This is an example base URL.
tags:
- name: Root
  description: The operations for the root resource.
- name: Watches
  description: Configuration data that will cause the rollout updates.
paths:
  /:
    get:
      tags:
      - Root
      summary: Get a list of top-level links
      operationId: root
      description: Get a list of top level links.
      responses:
        "200":
          description: OK.
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                json:
                  $ref: "#/components/examples/api"
            application/json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                json:
                  $ref: "#/components/examples/api"
  /watches:
    get:
      summary: Returns Watches
      tags:
      - Watches
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/watches"
              examples:
                json:
                  $ref: "#/components/examples/watches"
      operationId: getWatches
      description: Returns a list of all watches
    post:
      summary: Creates Watches
      tags:
      - Watches
      responses:
        "201":
          description: New watch created.
          headers:
            Date:
              description: date string for the time of the operation.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/watches"
              examples:
                json:
                  $ref: "#/components/examples/watches"
        "400":
          description: Input was badly formed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/errorResponse"
      operationId: createWatch
      description: Creates a single watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/watches"
            examples:
              json:
                $ref: "#/components/examples/watches"
        description: A watch attributes includes data.
components:
  schemas:
    watches:
      title: watches
      description: An object describing an area of the consul KV store to watch with
        the current index
      type: object
      additionalProperties:
        type: object
        properties:
          code:
            type: integer
          text:
            type: string
    link:
      title: Link
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method to invoke this endpoint.
        rel:
          type: string
          description: The relationship of this URL to the object.
        uri:
          type: string
          description: The relative URI of the REST endpoint.
        href:
          type: string
          description: The full URL of the REST endpoint.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type consumed/produced.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
    api:
      description: Representation of the API
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
        links:
          type: array
          description: The API's top-level links.
          items:
            $ref: "#/components/schemas/link"
    errorResponse:
      title: "Error"
      description: "The representation of an error."
      type: object
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The error message.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred
          items:
            $ref: "#/components/schemas/errorResponse"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
  examples:
    api:
      summary: Root links
      description: Response to root context that returns API root links.
      value: {"version": 1, "links": [{"method": "GET", "rel": "watches", "href": "/configReconciler/watches",
            "uri": "/configReconciler/watches"}, {"method": "POST", "rel": "createWatch",
            "href": "/configReconciler/watches", "uri": "/configReconciler/watches"}]}
    watches:
      summary: watches
      description: Response to request for watches
      value: {"sas-annotations": {"config/annotations": 623, "config/application": 2469},
        "sas-fonts": {"config/application": 2469, "config/fonts": 634}, "sas-notifications": {
          "config/application": 2469, "config/notifications": 2077}, "sas-types": {
          "config/application": 2469, "config/types": 722}}
    errorResponse:
      summary: Sample error response
      description: Example of an error response from the service
      value: {"version": 2, "httpStatusCode": 400, "errorCode": 1020, "message": "Field\
          \ blah is invalid for the target type.", "details": ["path: /configReconciler/watches",
          "correlator: 103aed3e-d183-459e-8c8f-f0c57013995f"]}
