---
openapi: 3.0.3
info:
  title: Data Agent Server Colocated
  description: Example showing how to send a binary blob to the server that will return
    an error.
  version: "1"
  termsOfService: https://www.sas.com/en_us/legal/copyright.html
  contact:
    name: SAS Developers
    email: devex@sas.com
    url: https://developer.sas.com
servers:
- url: http://example.com/dataAgentServerColocated
  description: This is an example of a base URL for colocated Cloud Data Exchange.
tags:
- name: Root
  description: The API root.
paths:
  /:
    post:
      operationId: root
      summary: Submit FSNET request (that is guaranteed to fail)
      description: Submits FSNET requests.
      tags:
      - Root
      requestBody:
        description: Binary blob payload
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
            examples:
              example-1:
                summary: A sample binary file
                value: R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
              examples:
                example-1:
                  summary: A sample binary file
                  value: R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                example-error1:
                  summary: Example error message with status code 400
                  value:
                    error: Invalid payload
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                example-error1:
                  summary: Example error message with status code 500
                  value:
                    error: Server error
components: {}
