---
openapi: "3.0.3"
info:
  version: "2"
  title: Data Sources Provider
  contact:
    name: SAS Developers
    url: https://developer.sas.com
    email: devex@sas.com
  description: >
    The Data Sources Provider API provides transformation of domain specific data
    to the common Data Sources model of data.
    This endpoints documented here are only a subset of the endpoints needed by the
    provider service.
tags:
- name: Providers
  description: Providers for Data Sources.
paths:
  /dataSourcesProvider:
    get:
      operationId: getDataSourcesProvider
      summary: Get provider
      description: Returns information about this current provider service.
      tags:
      - Providers
      responses:
        "200":
          description: The request succeeded.
          content:
            application/vnd.sas.data.provider+json:
              schema:
                $ref: "#/components/schemas/provider"
              examples:
                schemaval:
                  $ref: "#/components/examples/provider"
            application/vnd.sas.provider.summary+json:
              schema:
                $ref: "#/components/schemas/providerSummary"
              examples:
                schemaval:
                  $ref: "#/components/examples/providerSummary"
            application/json:
              schema:
                $ref: "#/components/schemas/provider"
              examples:
                schemaval:
                  $ref: "#/components/examples/provider"
        "401":
          description: Not authenticated
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                schemaval:
                  $ref: "#/components/examples/error401"
            application/json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                schemaval:
                  $ref: "#/components/examples/error401"
        "403":
          description: Forbidden - the user does not have permission to complete this
            request
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                schemaval:
                  $ref: "#/components/examples/error403"
            application/json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                schemaval:
                  $ref: "#/components/examples/error403"
servers:
- url: http://example.com/dataSourcesProviderContract
  description: server
components:
  examples:
    provider:
      summary: The provider resource.
      description: An example of newly created provider.
      value: {"id": "cas", "apiVersion": 2, "usesSessions": true, "sourceDefinitionsSupport": "none",
        "version": 2, "links": [{"method": "GET", "rel": "self", "href": "/dataSources/providers/cas",
            "uri": "/dataSources/providers/cas", "type": "application/vnd.sas.data.provider"},
          {"method": "GET", "rel": "alternate", "href": "/dataSources/providers/cas",
            "uri": "/dataSources/providers/cas", "type": "application/vnd.sas.data.provider.summary"},
          {"method": "GET", "rel": "dataSources", "href": "/dataSources/providers/cas/sources",
            "uri": "/dataSources/providers/cas/sources", "type": "application/vnd.sas.data.source"},
          {"method": "GET", "rel": "up", "href": "/dataSources/providers", "uri": "/dataSources/providers",
            "type": "application/vnd.sas.collection", "itemType": "application/vnd.sas.data.provider.summary"}]}
    providerSummary:
      summary: The summary of the provider resource.
      description: An example of summary for the provider.
      value: {"id": "cas", "version": 2, "links": [{"method": "GET", "rel": "self",
            "href": "/dataSources/providers/cas", "uri": "/dataSources/providers/cas",
            "type": "application/vnd.sas.data.provider"}]}
    error401:
      description: this is an example of an error that could be returned for unauthorized
        users
      summary: Unauthorized
      value:
        httpStatusCode: 401
        message: example error message
        version: 2
    error403:
      description: this is an example of an error that could be returned for unauthorized
        access
      summary: Forbidden
      value:
        httpStatusCode: 403
        message: example error message
        version: 2
  schemas:
    provider:
      type: object
      description: Information about a Provider
      properties:
        id:
          type: string
          description: >
            The unique provider identifier
        version:
          type: integer
          description: provider schema version
        apiVersion:
          type: integer
          description: provider API version
        usesSessions:
          type: boolean
          description: >
            Will be true if this provider supports sessions, false otherwise
        sourceDefinitionsSupport:
          type: string
          description: >
            Indicates to the dataSources service how it should handle source definition
            persistence for this provider.
            The possible values are none (no support) and providedByDataSources (data
            sources service stores source definitions
            for the provider).
          x-sas-since: "2"
        attributes:
          type: object
          description: Additional provider specific attributes
          additionalProperties: {}
        links:
          type: array
          description: Links that apply to this resource
          items:
            $ref: "#/components/schemas/link"
    providerSummary:
      type: object
      description: Information about a Provider summary
      properties:
        id:
          type: string
          description: >
            The unique provider identifier
        version:
          type: integer
          description: provider schema version
        links:
          type: array
          description: Links that apply to this resource
          items:
            $ref: "#/components/schemas/link"
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
    error2:
      title: Error
      type: object
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: "#/components/schemas/error2"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
