---
openapi: 3.0.3
info:
  title: Fraud Decisioning Config
  description: |
    Fraud Decisioning Config lays down solution specific configurations into your system, depending on licenses. This current version includes 
    message schemas. This API provides operations used to check the status of your system and see what level of SAS Fraud Decisioning your system
    is licensed for, as well as which solution configurations are laid down.
  version: "1"
  contact:
    name: SAS Developers
    url: "https://developer.sas.com"
    email: devex@sas.com
  termsOfService: "https://www.sas.com/en_us/legal/copyright.html"
servers:
- url: "http://mock-fraudDecisioningConfig.apifirst.unx.sas.com/fraudDecisioningConfig"
  description: kubernetes mock server
- url: "https://example.com/fraudDecisioningConfig"
  description: local mock server
tags:
- name: Root
  description: The operations for the root resource.
- name: Status
  description: The operations to get information on what configurations are included.
paths:
  /:
    get:
      tags:
      - Root
      summary: Return a list of top-level links
      description: Return a list of top-level links.
      operationId: root
      responses:
        "200":
          description: OK
          headers:
            Last-Modified:
              $ref: "#/components/headers/lastModifiedHeader"
            Location:
              $ref: "#/components/headers/locationHeader"
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                default:
                  $ref: "#/components/examples/api"
            application/json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                default:
                  $ref: "#/components/examples/api"
        "404":
          description: Service is not available
          headers:
            Last-Modified:
              $ref: "#/components/headers/lastModifiedHeader"
            Location:
              $ref: "#/components/headers/locationHeader"
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                default:
                  $ref: "#/components/examples/service_not_available_error_404"
            application/json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                default:
                  $ref: "#/components/examples/service_not_available_error_404"
  /status:
    get:
      summary: Return licensed level and solutions
      operationId: getStatus
      tags:
      - Status
      description: |
        This endpoint returns a description of what your system includes. This could be a Standard, Advanced, or Premier level, 
        and whatever solutions your system has licenses for.
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              $ref: "#/components/headers/contentType"
          content:
            application/vnd.sas.config.status+json:
              schema:
                $ref: "#/components/schemas/status"
              examples:
                default:
                  $ref: "#/components/examples/status"
            application/json:
              schema:
                $ref: "#/components/schemas/status"
              examples:
                default:
                  $ref: "#/components/examples/status"
        "404":
          description: Service is not available
          headers:
            Last-Modified:
              $ref: "#/components/headers/lastModifiedHeader"
            Location:
              $ref: "#/components/headers/locationHeader"
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                default:
                  $ref: "#/components/examples/service_not_available_error_404"
            application/json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                default:
                  $ref: "#/components/examples/service_not_available_error_404"
  /status/schemas:
    get:
      summary: Return licensed message schemas managed by sas-fraud-decisioning-config
      operationId: getSchemas
      tags:
      - Status
      description: |
        This endpoint returns a list of message schema summaries that give details about the managed message 
        schemas licensed in your sas-fraud-decisioning-config deployment
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              $ref: "#/components/headers/contentType"
          content:
            application/vnd.sas.collection+json:
              schema:
                $ref: "#/components/schemas/messageSchemaList"
              examples:
                default:
                  $ref: "#/components/examples/message_schema_list"
            application/json:
              schema:
                $ref: "#/components/schemas/messageSchemaList"
              examples:
                default:
                  $ref: "#/components/examples/message_schema_list"
        "404":
          description: Service is not available
          headers:
            Last-Modified:
              $ref: "#/components/headers/lastModifiedHeader"
            Location:
              $ref: "#/components/headers/locationHeader"
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                default:
                  $ref: "#/components/examples/service_not_available_error_404"
            application/json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                default:
                  $ref: "#/components/examples/service_not_available_error_404"
components:
  headers:
    locationHeader:
      description: Location of URI for the endpoint.
      schema:
        type: string
    lastModifiedHeader:
      description: Data and Time of last modification.
      schema:
        type: string
    etagHeader:
      description: An hash-code for the response resource.
      schema:
        type: string
    contentType:
      description: Content Type of returned content.
      schema:
        type: string
  schemas:
    status:
      title: Status
      description: Description of the SFD level and licensed solutions
      properties:
        level:
          type: string
          enum:
          - Standard
          - Advanced
          - Premier
        solutions:
          type: array
          items:
            type: string
    messageSchemaList:
      title: MessageSchemas
      description: A list of message schema summaries
      properties:
        items:
          type: array
          description: array of message schema summary objects
          items:
            allOf:
            - $ref: "#/components/schemas/messageSchemaSummary"
    error2:
      title: Error
      type: object
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: "#/components/schemas/error2"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
        links:
          description: The API's top-level links.
          type: array
          items:
            $ref: "#/components/schemas/link"
    messageSchemaSummary:
      title: MessageSchemaSummary
      description: Information about a message schema, including name, type, state,
        ID, and timestamp related fields.
      properties:
        id:
          type: string
          description: schema's unique identifier
        name:
          type: string
          description: name of the schema
        type:
          type: string
          description: type of the schema
        state:
          type: string
          description: state of the schema. For SFD managed schemas, this should always
            be Deployed.
          enum:
          - Developing
          - Deployment-Ready
          - Deployed
        revision:
          type: integer
        creationTimeStamp:
          type: string
        createdBy:
          type: string
        modifiedTimeStamp:
          type: string
        modifiedBy:
          type: string
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
  examples:
    message_schema_list:
      description: Return a list of the licensed message schemas manage by sas-fraud-decisioning-config
      value: {"items": [{"id": "184cce0d-9d29-4c3c-9ba6-0ced9dd246f0", "name": "Fraud\
              \ Decisioning Solution", "type": "variable_set_by_sas", "state": "Deployed",
            "revision": 2, "creationTimeStamp": "2023-05-28T02:36:55.107841Z", "createdBy": "sas.fraudDecisioningConfig",
            "modifiedTimeStamp": "2023-05-28T02:37:04.521693Z", "modifiedBy": "sas.fraudDecisioningConfig"},
          {"id": "7e2f9cca-6dbf-4d29-8d31-bc4fdccb7d7d", "name": "Fraud Decisioning\
              \ Customer", "type": "variable_set_by_sas", "state": "Deployed", "revision": 2,
            "creationTimeStamp": "2023-05-28T02:36:55.841972Z", "createdBy": "sas.fraudDecisioningConfig",
            "modifiedTimeStamp": "2023-05-28T02:37:04.711885Z", "modifiedBy": "sas.fraudDecisioningConfig"},
          {"id": "754cc93a-ebc0-4b0f-bc55-992a31dacbe7", "name": "Fraud Decisioning\
              \ Debit Account", "type": "variable_set_by_sas", "state": "Deployed",
            "revision": 2, "creationTimeStamp": "2023-05-28T02:36:56.92896Z", "createdBy": "sas.fraudDecisioningConfig",
            "modifiedTimeStamp": "2023-05-28T02:37:04.881846Z", "modifiedBy": "sas.fraudDecisioningConfig"},
          {"id": "b8278e3b-920b-49a4-83e9-4c76d9266d0c", "name": "Fraud Decisioning\
              \ Demographic", "type": "variable_set_by_sas", "state": "Deployed",
            "revision": 2, "creationTimeStamp": "2023-05-28T02:36:58.10382Z", "createdBy": "sas.fraudDecisioningConfig",
            "modifiedTimeStamp": "2023-05-28T02:37:05.025055Z", "modifiedBy": "sas.fraudDecisioningConfig"},
          {"id": "190d3861-7958-48c5-9683-2ecab49f0f98", "name": "Fraud Decisioning\
              \ Merchant Acquiring", "type": "variable_set_by_sas", "state": "Deployed",
            "revision": 2, "creationTimeStamp": "2023-05-28T02:36:58.908457Z", "createdBy": "sas.fraudDecisioningConfig",
            "modifiedTimeStamp": "2023-05-28T02:37:05.210077Z", "modifiedBy": "sas.fraudDecisioningConfig"},
          {"id": "50abc354-c493-4bbd-832c-11dfd5759985", "name": "Fraud Decisioning\
              \ Credit Card", "type": "variable_set_by_sas", "state": "Deployed",
            "revision": 2, "creationTimeStamp": "2023-05-28T02:36:59.773821Z", "createdBy": "sas.fraudDecisioningConfig",
            "modifiedTimeStamp": "2023-05-28T02:37:05.346878Z", "modifiedBy": "sas.fraudDecisioningConfig"},
          {"id": "23bafba0-8d78-43ec-83fd-abdfff99a712", "name": "Fraud Decisioning\
              \ Debit Card", "type": "variable_set_by_sas", "state": "Deployed", "revision": 2,
            "creationTimeStamp": "2023-05-28T02:37:01.347443Z", "createdBy": "sas.fraudDecisioningConfig",
            "modifiedTimeStamp": "2023-05-28T02:37:05.490332Z", "modifiedBy": "sas.fraudDecisioningConfig"},
          {"id": "2ffa059a-6be7-4a1f-bcfb-a77baf699305", "name": "Credit Card Decisioning",
            "type": "solution_by_sas", "state": "Deployed", "revision": 2, "creationTimeStamp": "2023-05-28T02:37:02.453652Z",
            "createdBy": "sas.fraudDecisioningConfig", "modifiedTimeStamp": "2023-05-28T02:37:05.639756Z",
            "modifiedBy": "sas.fraudDecisioningConfig"}, {"id": "3df47a6e-9402-4948-8884-dbc6bdbdd3b5",
            "name": "Debit Card Decisioning", "type": "solution_by_sas", "state": "Deployed",
            "revision": 2, "creationTimeStamp": "2023-05-28T02:37:03.929553Z", "createdBy": "sas.fraudDecisioningConfig",
            "modifiedTimeStamp": "2023-05-28T02:37:05.791424Z", "modifiedBy": "sas.fraudDecisioningConfig"}]}
    api:
      description: Return a list of API Links
      value: {"version": 1, "links": [{"method": "GET", "rel": "getAPI", "href": "/fraudDecisioningConfig",
            "uri": "/fraudDecisioningConfig", "responseType": "application/vnd.sas.api+json"},
          {"method": "GET", "rel": "getStatus", "href": "/fraudDecisioningConfig/status",
            "uri": "/fraudDecisioningConfig/status", "responseType": "application/vnd.sas.config.status+json"},
          {"method": "GET", "rel": "getSchemas", "href": "/fraudDecisioningConfig/status/schemas",
            "uri": "/fraudDecisioningConfig/status/schemas", "responseType": "application/vnd.sas.collection+json"}]}
    status:
      description: Return a description of the SFD level and licensed solutions
      value: {"level": "Premier", "solutions": ["SAS Fraud Decisioning Common", "SAS\
            \ Fraud Decisioning Card Fraud"]}
    service_not_available_error_404:
      description: Service not available 404 Response Example
      value: {"version": 2, "httpStatusCode": 404, "errorCode": 1000000, "message": "Service\
          \ not available"}
