---
openapi: 3.0.3
info:
  title: SAS Readiness
  version: "1"
  description: >
    Readiness checks the status of the SAS Viya deployment, and
    determines if it is ready for use. It performs all of its checks every 30 seconds.   After
    the software is deployed, readiness should be consulted to determine whether  the
    deployment is ready for use. Readiness is also a useful tool for  the administration
    of SAS Viya deployment throughout its life.
  termsOfService: "https://www.sas.com/en_us/legal/copyright.html"
  contact:
    name: "SAS Developers"
    email: "devex@sas.com"
    url: "https://developer.sas.com"
servers:
- url: http://example.com/readiness
  description: local mock server
tags:
- name: Root
  description: Contains the operations for the root resource.
- name: Settings
  description: Contains the operations for readiness settings.
paths:
  /:
    get:
      summary: Get a list of top-level links
      description: Get a list of top-level links.
      operationId: root
      tags:
      - Root
      responses:
        "200":
          description: OK.
          headers:
            Content-Type:
              schema:
                type: "string"
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                api:
                  $ref: "#/components/examples/getTopLevelResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                api:
                  $ref: "#/components/examples/getTopLevelResponse"
components:
  schemas:
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
  examples:
    getTopLevelResponse:
      summary: Response for top level.
      description: "Here is an example of using the GET request to retrieve the application/vnd.sas.api+json\
        \ representation of the APIs top-level links."
      value: {"version": 1, "links": []}
