---
openapi: 3.0.3
info:
  version: "1"
  title: Common Retail Data Platform
  description: >
    The retail data platform (RDP) will provide multiple benefits including a common
    ETL process, a shared data model, a flexible way of adding new source data to
    the RDP, and a consistent process to access and update the shared data.  If a
    consistent and well-structured access pattern can be established, the solutions
    would be able to align their designs to better integrate the Retail Suite of products.  In
    addition, the RDP could function as a foundational module could be sold as an
    offering that enables consulting efforts, partners, or “DIY” customers.
  contact:
    name: SAS Developers
    url: https://developer.sas.com
    email: devex@sas.com
servers:
- url: http://mock-retailData.apifirst.unx.sas.com/retailData
  description: kubernetes mock server
tags:
- name: Root
  description: The operations for the root resource.
paths:
  /:
    get:
      tags:
      - Root
      summary: Get a list of top-level links
      operationId: root
      description: Returns a list of links to the top-level collections surfaced through
        this API.
      responses:
        "200":
          description: OK
          content:
            "application/vnd.sas.api+json":
              schema:
                $ref: "#/components/schemas/api"
            "application/json":
              schema:
                $ref: "#/components/schemas/api"
          headers:
            Content-Type:
              required: true
              description: the content type
              schema:
                type: string
            Last-Modified:
              required: true
              description: The last modified date and time of the api.
              schema:
                type: string
        "404":
          description: Service is not available
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/error2"
            application/json:
              schema:
                $ref: "#/components/schemas/error2"
          headers:
            Content-Type:
              required: true
              description: The content type
              schema:
                type: string
            Last-Modified:
              description: Indicates the date and time at which the original resource
                was last modified.
              schema:
                type: string
                format: dateTime
components:
  schemas:
    error2:
      title: Error
      type: object
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: "#/components/schemas/error2"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
        links:
          description: The API's top-level links.
          type: array
          items:
            $ref: "#/components/schemas/link"
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
