---
openapi: 3.0.3
info:
  version: "2"
  title: SAS Drive Web Application and Configuration
  description: |
    Provides representations of SAS objects with regards to SAS Drive App.

    (!!) This API is deprecated as of 2024.12 Stable / 2025.03 LTS and will be removed in a future release. (!!)
  contact:
    name: SAS Developers
    url: https://developer.sas.com
    email: devex@sas.com
servers:
- url: http://example.com/SASDrive
  description: This is an example base URL.
tags:
- name: Root
  description: Contains the operations for the root resource.
- name: Commons
  description: Contains Commons operations.
- name: Settings
  description: Contains the operations for reading SAS Drive settings.
paths:
  /:
    get:
      summary: Get web application
      description: Returns HTML launcher that loads the SAS Drive application.
      operationId: root
      tags:
      - Root
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              description: The media type of the response body.
              schema:
                type: string
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/root"
              example:
                $ref: "#/components/schemas/root/example"
  /commons:
    get:
      summary: Get links for Commons endpoints
      description: Returns a settings link.
      operationId: getCommons
      tags:
      - Commons
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              description: The media type of the response body.
              schema:
                type: string
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/commons"
              example:
                $ref: "#/components/schemas/commons/example"
            application/json:
              schema:
                $ref: "#/components/schemas/commons"
              example:
                $ref: "#/components/schemas/commons/example"
  /commons/settings:
    get:
      summary: Get configuration settings
      description: >
        Returns a set of attributes acquired from the Configuration API. These
        attributes are configurable via SAS Environment Manager.
      operationId: getSettings
      tags:
      - Settings
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              description: The media type of the response body.
              schema:
                type: string
          content:
            application/vnd.sas.attributes+json:
              schema:
                $ref: "#/components/schemas/settings"
              example:
                $ref: "#/components/schemas/settings/example"
            application/json:
              schema:
                $ref: "#/components/schemas/settings"
              example:
                $ref: "#/components/schemas/settings/example"
components:
  schemas:
    root:
      description: Root schema.
      type: string
      format: html
      example: |
        <!DOCTYPE html>
        <html>
          <head>
            <script nonce="">performance && performance.mark("sas-hc-startup");</script>
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <link rel="icon" type="image/x-icon" href="/SASDrive/resources/shcb202206230647/sas/hc/ui/commons/themes/sas_corporate/img/ico/SASLogo_toolbar.ico"/>
            <meta content="/SASDrive/resources/shcb202206230647/sas/hc/ui/commons/themes/sas_corporate/img/ico/SASLogo_toolbar.ico" itemprop="image">
            <link rel="stylesheet" href="/SASDrive/resources/shcb202206230647/sas/hc/ui/commons/themes/sas_corporate/splash.css" media="screen">
            <meta charset="UTF-8">

            <link rel="manifest" crossOrigin="use-credentials" href="/SASDrive/resources/pwa/sas-manifest.json"/>
          </head>
          <body class="sapUiBody">
            <div>This is the SAS Drive web application.</div>

            <script src="/SASDrive/resources/shcb202206230647/sap-ui-custom.js" id="sap-ui-bootstrap" data-loading="Loading" data-still-loading="Still Loading"></script>
            <script nonce="" type="text/javascript" id="hc-init">
              sap.ui.getCore().attachInit(function(){
              sap.ui.require(['sas/hc/ui/core/util'], function(util){
                util._doOnAppSwitcherBootstrap("SASDrive");
                })
              });
            </script>
          </body>
        </html>
    commons:
      description: Schema for /SASDrive/commons.
      allOf:
      - $ref: "#/components/schemas/api"
      example:
        version: 1
        links:
        - method: GET
          rel: settings
          href: /SASDrive/commons/settings
          uri: /SASDrive/commons/settings
          type: application/vnd.sas.attributes
    settings:
      description: Schema for /SASDrive/commons/settings.
      allOf:
        # the first object overrides the second object
      - type: object
        properties:
          attributes:
            type: object
            description: The map of attribute names to values.
            additionalProperties: false
            properties:
              contentRefreshEnabled:
                description: "**Check for content changes**: Specifies whether SAS\
                  \ Drive automatically checks for content changes in the current\
                  \ tab, and enables content caching when you change tabs."
                type: boolean
                default: false
              contentRefreshInterval:
                description: "**Content refresh interval**: Specifies the interval\
                  \ (in seconds) at which SAS Drive checks for content changes in\
                  \ the current tab. If there are changes, a notification appears\
                  \ with a Refresh button.\n\nNote: This option has no effect if the\
                  \ \"Check for content changes\" parameter is not enabled."
                type: integer
                default: 300
              contentRefreshMinDelay:
                description: "**Cached content threshold**: Specifies a time threshold\
                  \ (in seconds) for displaying cached content when you navigate to\
                  \ a different tab. By default, cached tab content is displayed if\
                  \ the tab was previously viewed within the last 30 seconds. When\
                  \ you view a different tab, the content is refreshed immediately\
                  \ if the cache is older than the specified value.\n\nNote: This\
                  \ option has no effect if the \"Check for content changes\" parameter\
                  \ is not enabled."
                type: integer
                default: 30
              copyLinkChangePerm:
                description: "**Copy link change permissions**: Enables changing copy\
                  \ link permissions."
                type: boolean
                default: true
              copyLinkEnabled:
                description: "**Copy link**: Enables the 'Copy Link' window."
                type: boolean
                default: true
              copyLinkExpires:
                description: "**Copy link expiration**: The expiration date for links,\
                  \ in the form YYYYMMDD. The default is no expiration date."
                type: string
                default: ""
              defaultToListView:
                description: "**Default to list view**: Shows the content area as\
                  \ a list table by default."
                type: boolean
                default: false
              myOrganization:
                description: "**My organization**: The group ID for the organization.\
                  \ The value should be a valid group ID. The default is no ID."
                type: string
                default: ""
              openInNewTabEnabled:
                description: "**View in new tab**: Enables the 'View in new tab' context\
                  \ menu item."
                type: boolean
                default: false
              projectsUIEnabled:
                description: "**Projects UI enabled**: Enables the deprecated Projects\
                  \ interface."
                type: boolean
                default: false
              useDefaultThumbnails:
                description: "**Use default thumbnails**: Disables the generation\
                  \ of dynamic thumbnails for content in the tile view."
                type: boolean
                default: false
      - $ref: "#/components/schemas/attributes"
      example:
        version: 1
        attributes:
          contentRefreshEnabled: false
          contentRefreshInterval: 300
          contentRefreshMinDelay: 30
          copyLinkChangePerm: true
          copyLinkEnabled: true
          copyLinkExpires: ""
          defaultToListView: false
          myOrganization: ""
          openInNewTabEnabled: false
          projectsUIEnabled: false
          useDefaultThumbnails: false
        links:
        - method: GET
          rel: self
          href: /SASDrive/commons/settings
          uri: /SASDrive/commons/settings
          type: application/vnd.sas.attributes
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
        links:
          description: The API's top-level links.
          type: array
          items:
            $ref: "#/components/schemas/link"
    attributes:
      title: Attributes
      description: Contains a set of attributes in the form of a map from string names
        to arbitrary values. The values may be strings, numbers, booleans, arrays,
        objects or null.
      x-sas-media-type:
        name: application/vnd.sas.attributes
        version: 1
      required:
      - version
      - attributes
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
        description:
          type: string
          description: A description of the set of attributes.
        label:
          type: string
          description: A brief description or label for the set of attributes.
        attributes:
          type: object
          description: 'The map of attribute names to values.  The set of names is
            open, though individual services may define a closed set needed for a
            given resource in that service. The value of each attribute may be of
            types: number, string, boolean, array, or object.  Although property this
            is required, the mapping object can be empty, unless stated otherwise
            by specific documentation for resources where the application/vnd.sas.attributes
            type is used.'
          additionalProperties: true
        links:
          description: Links to associated resources and operations. APIs may provide
            links for the link relations `self', `update` (to replace the attributes),
            `patch` (to update some attributes) or others.
          type: array
          items:
            $ref: "#/components/schemas/link"
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
