---
openapi: 3.0.3
info:
  version: "1"
  title: Real-Time Watchlist Screening
  description: |
    The Real-Time Watchlist Screening API supports management of objects used during screening operations.
  termsOfService: "https://www.sas.com/en_us/legal/copyright.html"
  contact:
    name: SAS Developers
    email: devex@sas.com
    url: "https://developer.sas.com"
servers:
- url: "http://example.com/SASWatchlistScreening"
  description: This is an example of a base URL.
tags:
- name: Root
  description: Contains operations for the root resource.
paths:
  /:
    get:
      operationId: root
      summary: Get the list of watchlist screening resources
      description: Returns the watchlist screening resources.
      tags:
      - Root
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                json:
                  $ref: "#/components/examples/rootResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                json:
                  $ref: "#/components/examples/rootResponse"
components:
  schemas:
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
        links:
          type: array
          description: The API"s top-level links.
          items:
            $ref: "#/components/schemas/link"
    link:
      title: Link
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method to invoke this endpoint.
        rel:
          type: string
          description: The relationship of this URL to the object.
        uri:
          type: string
          description: The relative URI of the REST endpoint.
        href:
          type: string
          description: The full URL of the REST endpoint.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type consumed/produced.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
  examples:
    rootResponse:
      summary: Root response
      description: List of endpoints for the watchlist screening service
      value: {"links": [{"method": "GET", "rel": "presets", "href": "/SASWatchlistScreening/presets",
            "uri": "/SASWatchlistScreening/presets", "type": "application/vnd.sas.collection",
            "itemType": "application/json"}], "version": 4}
