---
openapi: 3.0.3
info:
  title: Visual Investigator Entity Resolution
  description: >-
    The VI Entity Resolution API provides access to the background entity resolution
    process
    in Visual Investigator. This provides clients with the ability to trigger new
    entity resolution jobs
    and to rebuild the resolved entities within a VI system.
    Version 2 of this API serves both 10.8 and Viya 4 versions of VI Entity Resolution.  As
    of 2023.03,
    this API is deprecated and will no longer be usable.
  version: '2'
  contact:
    name: SAS Developers
    url: 'https://developer.sas.com'
    email: devex@sas.com
tags:
- name: Root
  description: The root of the API.
- name: Entity Resolution
  description: Entity resolution related endpoints.
paths:
  /:
    get:
      tags:
      - Root
      operationId: root
      summary: Get a list of top-level links
      description: Returns a list of links to the top-level resources surfaced through
        this API. This will include the resources that access the analytics provided
        by CAS e.g. "centrality".
      responses:
        '200':
          description: OK
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: '#/components/schemas/api'
              examples:
                api:
                  $ref: '#/components/examples/api'
            application/json:
              schema:
                $ref: '#/components/schemas/api'
              examples:
                api:
                  $ref: '#/components/examples/api'
  /jobs:
    get:
      tags:
      - Entity Resolution
      operationId: getJobs
      summary: Retrieve the collection containing the running or previously completed
        entity resolution jobs
      description: Retrieve a collection of the running or previously completed entity
        resolution jobs. The service only includes a history of one job. The item
        media type is application/vnd.sas.entity.resolution.job.
      responses:
        '200':
          description: OK
          content:
            application/vnd.sas.collection+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/entityResolutionJob'
              examples:
                entityResolutionJobCollection:
                  $ref: '#/components/examples/entityResolutionJobCollection'
            application/json:
              schema:
                $ref: '#/components/schemas/entityResolutionJobCollection'
              examples:
                entityResolutionJobCollection:
                  $ref: '#/components/examples/entityResolutionJobCollection'
    post:
      tags:
      - Entity Resolution
      operationId: createJob
      summary: Start a new instance of the entity resolution job
      description: Starts a new background instance of the entity resolution process.
        No additional input is required hence no consumable media types. Only a single
        job can be run at a time. The state and results of the job can be queried
        using additional resources exposed by the REST API.
      responses:
        '202':
          description: Job has been created and scheduled for processing
          headers:
            Location:
              description: The URL of the created entity resolution job.
              schema:
                type: string
          content:
            application/vnd.sas.entity.resolution.job+json:
              schema:
                $ref: '#/components/schemas/entityResolutionJob'
              examples:
                entityResolutionJob:
                  $ref: '#/components/examples/entityResolutionJob'
            application/json:
              schema:
                $ref: '#/components/schemas/entityResolutionJob'
              examples:
                entityResolutionJob:
                  $ref: '#/components/examples/entityResolutionJob'
        '409':
          description: Conflict - an entity resolution job is currently pending or
            running. Multiple jobs cannot be run at the same time.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                error2Response409:
                  $ref: '#/components/examples/error2Response409'
            application/json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                error2Response409:
                  $ref: '#/components/examples/error2Response409'
  /jobs/{jobId}:
    get:
      tags:
      - Entity Resolution
      operationId: getJob
      summary: Get the details of a currently running entity resolution job
      description: 'Retrieves the details of a currently running entity resolution
        job including the status, results and other job related data.'
      parameters:
      - name: jobId
        description: The unique identifier of the job.
        in: path
        required: true
        schema:
          type: string
          format: object-id
      responses:
        '200':
          description: OK
          content:
            application/vnd.sas.entity.resolution.job+json:
              schema:
                $ref: '#/components/schemas/entityResolutionJob'
              examples:
                entityResolutionJob:
                  $ref: '#/components/examples/entityResolutionJob'
            application/json:
              schema:
                $ref: '#/components/schemas/entityResolutionJob'
              examples:
                entityResolutionJob:
                  $ref: '#/components/examples/entityResolutionJob'
        '404':
          description: No job with the specified job ID has been found
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                error2Response404:
                  $ref: '#/components/examples/error2Response404'
            application/json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                error2Response404:
                  $ref: '#/components/examples/error2Response404'
  /jobs/{jobId}/state:
    get:
      tags:
      - Entity Resolution
      operationId: getJobState
      summary: Get the current state of an entity resolution job
      description: 'Returns the current state of an entity resolution job. This can
        be one of: pending, running, interrupted, completed, cancelled, failed.'
      parameters:
      - name: jobId
        description: The unique identifier of the job.
        in: path
        required: true
        schema:
          type: string
          format: object-id
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples:
                jobState:
                  $ref: '#/components/examples/jobState'
        '404':
          description: No job with the specified job ID has been found
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                error2Response404:
                  $ref: '#/components/examples/error2Response404'
            application/json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                error2Response404:
                  $ref: '#/components/examples/error2Response404'
servers:
- url: 'https://example.com/svi-entity-resolution'
  description: An example URL including the base path for this API
components:
  schemas:
    entityResolutionJobCollection:
      description: Collection that represents the current state of entity resolution
        jobs
      title: Entity resolution job collection
      allOf:
      - $ref: '#/components/schemas/baseCollection2'
      - type: object
        properties:
          items:
            type: array
            description: Array containing entity resolution jobs.
            items:
              $ref: '#/components/schemas/entityResolutionJob'
    entityResolutionJob:
      description: Represents the current state of an entity resolution job
      title: Entity resolution job
      x-sas-type: EntityResolutionJob
      x-sas-media-type:
        name: application/vnd.sas.entity.resolution.job
        version: 1
      required:
      - id
      - version
      - state
      - creationTimeStamp
      properties:
        id:
          type: string
          description: The system-assigned unique ID for this object.
        state:
          type: string
          enum:
          - pending
          - running
          - interrupted
          - completed
          - cancelled
          - failed
          description: The current state of the job.
        creationTimeStamp:
          type: string
          format: date-time
          description: The date-time when the entity resolution job was created.
        error:
          $ref: '#/components/schemas/error2'
        version:
          type: integer
          format: int32
          description: The version of this media type.
        links:
          type: array
          items:
            $ref: '#/components/schemas/link'
          description: Links to related resources/actions.
    error2:
      type: object
      title: Error
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: '#/components/schemas/error2'
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: '#/components/schemas/link'
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
    link:
      title: Link
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: 'If this is a link to a container, `itemType` is the media
            type or link type for the items in the container.'
        responseType:
          type: string
          description: 'The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.'
        responseItemType:
          type: string
          description: 'The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.'
    baseCollection2:
      title: Base Collection
      description: This is a base schema used to define paginated collections of resources.
        This base schema is extended by other schemas in APIs by adding an 'items'
        array property. These extensions define the application/vnd.sas.collection
        media type (version 2)
      properties:
        name:
          type: string
          description: The name of the collection.
        start:
          type: integer
          description: The zero-based index of the first item in the collection.
          format: int64
        limit:
          type: integer
          description: The number of items that were requested for the collection.
        count:
          type: integer
          description: If populated indicates the number of items in the collection.
          format: int64
        accept:
          type: string
          description: A space-delimited list of media types from which an `Accept`
            header may be constructed.
        links:
          type: array
          description: The links that apply to the collection.
          items:
            $ref: '#/components/schemas/link'
        version:
          type: integer
          description: The version number of the collection representation. This representation
            is version 2.
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
        links:
          description: The API's top-level links.
          type: array
          items:
            $ref: '#/components/schemas/link'
  examples:
    api:
      description: "An example of a response from /svi-entity-resolution listing top\
        \ level links."
      value:
        version: 1
        links:
        - method: GET
          rel: jobs
          href: "/svi-entity-resolution/jobs"
          uri: "/svi-entity-resolution/jobs"
          type: application/vnd.sas.collection
          itemType: application/vnd.sas.entity.resolution.job
        - method: POST
          rel: startJob
          href: "/svi-entity-resolution/jobs"
          uri: "/svi-entity-resolution/jobs"
          responseType: application/vnd.sas.entity.resolution.job
    entityResolutionJob:
      description: "A model representing an entity resolution job."
      value:
        version: 1
        id: 2bd19bc6-fe38-4b58-84ca-1185e63a5b6d
        state: completed
        creationTimeStamp: '2016-08-22T14:54:45.104Z'
        links:
        - method: GET
          rel: up
          href: "/svi-entity-resolution/jobs"
          uri: "/svi-entity-resolution/jobs"
          type: application/vnd.sas.collection
          itemType: application/vnd.sas.entity.resolution.job
        - method: GET
          rel: self
          href: "/svi-entity-resolution/jobs/2bd19bc6-fe38-4b58-84ca-1185e63a5b6d"
          uri: "/svi-entity-resolution/jobs/2bd19bc6-fe38-4b58-84ca-1185e63a5b6d"
          type: application/vnd.sas.entity.resolution.job
        - method: GET
          rel: state
          href: "/svi-entity-resolution/jobs/2bd19bc6-fe38-4b58-84ca-1185e63a5b6d/state"
          uri: "/svi-entity-resolution/jobs/2bd19bc6-fe38-4b58-84ca-1185e63a5b6d/state"
          type: text/plain
    entityResolutionJobCollection:
      description: "A collection of entity resolution jobs."
      value:
        version: 2
        name: items
        accept: application/vnd.sas.entity.resolution.job
        count: 1
        start: 0
        limit: 10
        items:
        - version: 1
          id: b8bcc51e-5f06-42ea-b7ba-1ddd6efa64b0
          state: completed
          creationTimeStamp: 2016-08-22T11:47:57.700000Z
          links:
          - method: GET
            rel: up
            href: /svi-entity-resolution/jobs
            uri: /svi-entity-resolution/jobs
            type: application/vnd.sas.collection
            itemType: application/vnd.sas.entity.resolution.job
          - method: GET
            rel: self
            href: /svi-entity-resolution/jobs/b8bcc51e-5f06-42ea-b7ba-1ddd6efa64b0
            uri: /svi-entity-resolution/jobs/b8bcc51e-5f06-42ea-b7ba-1ddd6efa64b0
            type: application/vnd.sas.entity.resolution.job
          - method: GET
            rel: state
            href: /svi-entity-resolution/jobs/b8bcc51e-5f06-42ea-b7ba-1ddd6efa64b0/state
            uri: /svi-entity-resolution/jobs/b8bcc51e-5f06-42ea-b7ba-1ddd6efa64b0/state
            type: text/plain
        links:
          method: GET
          rel: self
          href: /svi-entity-resolution/jobs
          uri: /svi-entity-resolution/jobs
          type: application/vnd.sas.collection
          itemType: application/vnd.sas.entity.resolution.job
    error2Response404:
      description: 'An example of a 404 not found error message.'
      value:
        errorCode: 0
        message: Job not found.
        traceId: 6a54911d533b0da8
        links: []
        version": 2
        httpStatusCode: 404
    error2Response409:
      description: 'An example of a 409 conflict error message.'
      value:
        errorCode: 66108
        message: An entity-resolution job is already running.
        traceId: 2a54911d533b8aa8
        links: []
        version": 2
        httpStatusCode: 409
    jobState:
      description: 'A description of the state of a job. This can be one of: pending,
        running, interrupted, completed, cancelled, failed.'
      value: "running"
