---
openapi: 3.0.3
info:
  title: Scenario Administration
  contact:
    name: SAS Developers
    url: "https://developer.sas.com"
    email: "devex@sas.com"
  description: The SAS Visual Investigator Scenario Administration service provides
    anomaly detection authoring and surveillance capabilities.
  version: '1'
tags:
- name: Root
  description: The operations for the root resource.
- name: Jobs
  description: The operations for the Scenario Administration jobs.
paths:
  /:
    get:
      tags:
      - Root
      summary: Get a list of top-level links
      description: Returns the links to the top-level resources for the API.
      operationId: root
      responses:
        '200':
          description: The request succeeded.
          headers:
            Content-Type:
              description: The Content Type of the response.
              schema:
                type: string
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                schemaval:
                  $ref: '#/components/examples/api'
            application/json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                schemaval:
                  $ref: '#/components/examples/api'
  /jobs/{jobId}/status:
    parameters:
    - name: jobId
      description: The unique identifier of the job.
      in: path
      required: true
      schema:
        type: string
    get:
      tags:
      - Jobs
      operationId: getJobStatus
      summary: Get the status of a job
      description: Returns the status of the specified job.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobStatus"
              examples:
                shemaval:
                  $ref: "#/components/examples/jobStatusExample"
            application/vnd.sas.fcs.vsd.job.status+json:
              schema:
                $ref: "#/components/schemas/jobStatus"
              examples:
                shemaval:
                  $ref: "#/components/examples/jobStatusExample"
        '404':
          description: Job not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                schemaval:
                  $ref: "#/components/examples/sasErrorExample"
            application/vnd.sas.error:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                schemaval:
                  $ref: "#/components/examples/sasErrorExample"
servers:
- url: 'https://example.com/svi-vsd-service'
  description: An example URL including the base path for this API.
components:
  examples:
    api:
      description: An example of the Scenario Administration service API.
      value:
        version: 1
        links: []
    sasErrorExample:
      description: An example of a SAS error object.
      value:
        message: An error occurred when processing your request.
        id: DH9999
        errorCode: 9999
        httpStatusCode: 400
        details:
        - See the log for additional details.
        remediation: Resolve the error and then resubmit the request.
    jobStatusExample:
      description: A sample job status.
      value: {"description": "Run the versioned flow \"InsuranceClaimFlow\".", "id": "Id\
          \ Value", "status": "COMPLETED", "subTasks": {"tdc_claim": "completed",
          "Too Many Claims With No Police Report": "completed", "Abnormally Large Reserve": "completed",
          "Replicate Events": "completed", "Deliver Events to Alert Service": "completed",
          "Deduplicate Events": "completed", "Too Many Claims From Same IP Address": "completed",
          "Filter Events for Alert Service": "completed"}}
  schemas:
    #/components/schemas/jobStatus"
    jobStatus:
      title: Job Status
      description: A representation of the Scenario Administration job status.
      properties:
        description:
          type: string
          description: The description of the job.
        id:
          type: string
          description: The unique identifier of the job.
        status:
          type: string
          enum: ["CREATED", "PENDING", "RUNNING", "CANCELLED", "COMPLETED", "FAILED",
            "REVERTED", "INVALID"]
          description: The possible values that indicate the status of a job.
        subTasks:
          type: object
          additionalProperties:
            type: string
          description: A collection of key-value strings for sub-tasks.
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
        links:
          description: The API's top-level links.
          type: array
          items:
            $ref: "#/components/schemas/link"
    error2:
      title: Error
      type: object
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: "#/components/schemas/error2"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
