---
openapi: 3.0.3
info:
  version: "3"
  title: Web Renderer
  description: >
    Web Renderer API provides resources for generating PDFs and images from
    HTML sources using headless Chromium printing.
  termsOfService: "https://www.sas.com/en_us/legal/copyright.html"
  contact:
    name: "SAS Developers"
    email: "devex@sas.com"
    url: "https://developer.sas.com"
tags:
- name: Root
  description: The operations for the root resource.
- name: PDF
  description: The operations for PDF rendering.
- name: Image
  description: The operations for Image rendering.
paths:
  /:
    get:
      tags:
      - Root
      summary: Get a list of top-level links
      operationId: root
      description: Returns a list of links to the top-level collections surfaced through
        this API.
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                api:
                  $ref: '#/components/examples/getLinks'
            application/json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                api:
                  $ref: '#/components/examples/getLinks'
        "404":
          description: Service is not available
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                api:
                  $ref: '#/components/examples/error404'
            application/json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                api:
                  $ref: '#/components/examples/error404'
  /pdf:
    post:
      tags:
      - PDF
      summary: Render PDF
      operationId: createPdf
      description: >
        Render a PDF document. Accepts payload of media type
        application/vnd.sas.web.rendering.options+json. <br><br>
        Returned items will be of media type application/pdf.
        Response body will be the rendered PDF.
      parameters:
      - name: packageUri
        in: query
        description: HTML package uri
        required: false
        schema:
          type: string
      - name: filename
        in: query
        description: Filename to append to link.  (default download.pdf)
        required: false
        schema:
          type: string
          default: download.pdf
      requestBody:
        description: ""
        required: true
        content:
          application/vnd.sas.web.rendering.options+json:
            schema:
              $ref: "#/components/schemas/renderingOptionsPdf"
            examples:
              api:
                $ref: "#/components/examples/postRenderPdf"
          application/vnd.sas.web.rendering.options+xml:
            schema:
              $ref: "#/components/schemas/renderingOptionsPdf"
            examples:
              api:
                $ref: "#/components/examples/postRenderPdf"
          application/json:
            schema:
              $ref: "#/components/schemas/renderingOptionsPdf"
            examples:
              api:
                $ref: "#/components/examples/postRenderPdf"
          application/xml:
            schema:
              $ref: "#/components/schemas/renderingOptionsPdf"
            examples:
              api:
                $ref: "#/components/examples/postRenderPdf"
      responses:
        "201":
          description: success. PDF has been created.
          headers:
            Content-Type:
              schema:
                type: string
            Location:
              description: Not used. All data return in response body.
              schema:
                type: string
          content:
            application/pdf:
              schema:
                $ref: "#/components/schemas/pdf"
              examples:
                api:
                  $ref: "#/components/examples/postRenderPdf"
        "400":
          description: Bad Request
          content:
            application/vnd.sas.error+json;charset=utf-8;version=2:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                api:
                  $ref: '#/components/examples/error400'
  /image:
    post:
      tags:
      - Image
      summary: Render image
      operationId: createImage
      description: >
        Render an image. Accepts payload of media type
        application/vnd.sas.web.rendering.image.options+json. <br><br>
        Returned items will be of media type image/png or image/jpeg.
        Response body will be the rendered image.
      parameters:
      - name: packageUri
        in: query
        description: HTML package uri
        required: false
        schema:
          type: string
      - name: filename
        in: query
        description: Filename to append to link.  (default download.png)
        required: false
        schema:
          type: string
          default: download.png
      requestBody:
        description: ""
        required: true
        content:
          application/vnd.sas.web.rendering.image.options+json:
            schema:
              $ref: "#/components/schemas/renderingOptionsImage"
            examples:
              api:
                $ref: "#/components/examples/postRenderImage"
          application/vnd.sas.web.rendering.image.options+xml:
            schema:
              $ref: "#/components/schemas/renderingOptionsImage"
            examples:
              api:
                $ref: "#/components/examples/postRenderImage"
          application/json:
            schema:
              $ref: "#/components/schemas/renderingOptionsImage"
            examples:
              api:
                $ref: "#/components/examples/postRenderImage"
          application/xml:
            schema:
              $ref: "#/components/schemas/renderingOptionsImage"
            examples:
              api:
                $ref: "#/components/examples/postRenderImage"
      responses:
        "201":
          description: success. Image has been created.
          headers:
            Content-Type:
              schema:
                type: string
            Location:
              description: Not used. All data return in response body.
              schema:
                type: string
          content:
            application/jpeg:
              schema:
                $ref: "#/components/schemas/image"
              examples:
                api:
                  $ref: "#/components/examples/postRenderImage"
        "400":
          description: Bad Request
          content:
            application/vnd.sas.error+json;charset=utf-8;version=2:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                api:
                  $ref: '#/components/examples/error400'
servers:
- url: https://example.com/webRenderer
  description: Web Renderer PDF Server
components:
  schemas:
    pdf:
      type: object
      description: PDF document.
    image:
      type: object
      description: JPEG or PNG image.
    renderingOptionsPdf:
      description: Request options for PDF rendering
      type: object
      properties:
        version:
          type: integer
          default: 3
          description: This media type's schema version number. (Current version 3)
        packageUri:
          type: string
          default: ""
          description: Optional HTML package uri to render. Required if url or html
            is not provided.
        url:
          type: string
          default: ""
          description: Optional valid url to render. Required if packageUri or html
            is not provided.  New in version 2.
        html:
          type: string
          default: ""
          description: Optional valid HTML to render. Required if packageUri or url
            is not provided.
        awaitReady:
          type: boolean
          default: false
          description: Waits for the loaded webpage to set "sasWebRendererReady" on
            window before rendering.  Times out after the lesser of the awaitTimeout
            setting or 5 min. New in version 2.
        awaitTimeout:
          type: number
          default: 0
          description: The number of milliseconds to wait before rendering.  If awaitReady
            is true, it is the number of milliseconds to wait for the ready status
            to be signalled.  Maximum is 300,000 (5 min.). New in version 2.
        height:
          type: string
          default: 11in
          description: A non-negative number optionally followed by one of the following
            units ( in , cm , mm , px ). Default=11in
        width:
          type: string
          default: 8.5in
          description: A non-negative number optionally followed by one of the following
            units ( in , cm , mm , px ). Default=8.5in
        marginTop:
          type: string
          default: .25in
          description: A non-negative number optionally followed by one of the following
            units ( in , cm , mm , px ). Default=.25in
        marginBottom:
          type: string
          default: .25in
          description: A non-negative number optionally followed by one of the following
            units ( in , cm , mm , px ). Default=.25in
        marginLeft:
          type: string
          default: .25in
          description: A non-negative number optionally followed by one of the following
            units ( in , cm , mm , px )). Default=.25in
        marginRight:
          type: string
          default: .25in
          description: A non-negative number optionally followed by one of the following
            units ( in , cm , mm , px ). Default=.25in
        scale:
          type: number
          default: 1
          description: Scale of the webpage rendering. Scale amount must be between
            0.1 and 2. Default=1.
        printBackground:
          type: boolean
          default: false
          description: Print background of the webpage rendering. Print background
            must be true or false. Default=false.
        landscape:
          type: boolean
          default: false
          description: Set the orientation to landscape. Landscape must be true or
            false. Default=false.
        displayHeaderFooter:
          type: boolean
          default: false
          description: Display header and footer. Must be true or false. Default=false.
        headerTemplate:
          type: string
          default: ""
          description: HTML template for the header. Used when displayHeaderFooter
            is true.
        footerTemplate:
          type: string
          default: ""
          description: HTML template for the footer. Used when displayHeaderFooter
            is true.
    renderingOptionsImage:
      description: Request options for image rendering
      type: object
      properties:
        version:
          type: integer
          default: 1
          description: This media type's schema version number. (Current version 1)
        packageUri:
          type: string
          default: ""
          description: Optional HTML package uri to render. Required if url or html
            is not provided.
        url:
          type: string
          default: ""
          description: Optional valid url to render. Required if packageUri or html
            is not provided.
        html:
          type: string
          default: ""
          description: Optional valid HTML to render. Required if packageUri or url
            is not provided.
        awaitReady:
          type: boolean
          default: false
          description: Waits for the loaded webpage to set "sasWebRendererReady" on
            window before rendering.  Times out after the lesser of the awaitTimeout
            setting or 5 min.
        awaitTimeout:
          type: number
          default: 0
          description: The number of milliseconds to wait before rendering.  If awaitReady
            is true, it is the number of milliseconds to wait for the ready status
            to be signalled.  Maximum is 300,000 (5 min.).
        clipX:
          type: string
          default: ""
          description: Optional x-coordinate of top-left corner of clip area
        clipY:
          type: string
          default: ""
          description: Optional y-coordinate of top-left corner of clip area
        clipWidth:
          type: string
          default: ""
          description: Optional width of the clip area
        clipHeight:
          type: string
          default: ""
          description: Optional height of the clip area
        fullPage:
          type: boolean
          default: false
          description: Capture the full scrollable page (true) or just the viewport
            (false).
        omitBackground:
          type: boolean
          default: false
          description: True to allow png images to have transparent backgrounds.
        type:
          type: string
          default: png
          description: Specify "png" for png images and "jpeg" for jpeg.
        quality:
          type: integer
          default: 0
          description: For jpeg only, set the quality from 0 to 100.
    error2:
      title: Error
      type: object
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: "#/components/schemas/error2"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
        links:
          description: The API's top-level links.
          type: array
          items:
            $ref: "#/components/schemas/link"
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
  examples:
    getLinks:
      summary: Response to GET commons settings.
      description: Here is an example of using the GET request to retrieve the application/vnd.sas.api+json
        representation of the APIs top-level links.
      value:
        version: 1
        links:
        - method: GET
          rel: commonsSettings
          href: /webRenderer/commons/settings
          uri: /webRenderer/commons/settings
          type: application/vnd.sas.attributes+json
        - method: POST
          rel: pdf
          href: /webRenderer/pdf
          uri: /webRenderer/pdf
          type: application/pdf
        - method: POST
          rel: pdf
          href: /webRenderer/image
          uri: /webRenderer/image
          type: application/png
    error400:
      summary: Server received a bad request.
      description: Here is an example of the error received when the Web Renderer
        server receives a bad request.
      value:
        version: 1
        httpStatusCode: 400
        message: An error was detected in the request
    error404:
      summary: Server not available.
      description: Here is an example of the error received when the Web Renderer
        server is unavailable.
      value:
        version: 1
        httpStatusCode: 404
        message: There is no handler defined for the path
    postRenderPdf:
      summary: Render a PDF Document
      description: Here is an example of using the POST request to render a PDF document
      value:
        html: html_body
        width: 500px
        height: 3in
        marginTop: 10px
        marginBottom: 10px
        marginLeft: 3in
        marginRight: 0in
        scale: 1.0
        displayHeaderFooter: true
        headerTemplate: HTML content
        footerTemplate: HTML content
    postRenderImage:
      summary: Render an Image
      description: Here is an example of using the POST request to render an Image
      value:
        html: html_body
        awaitReady: false
        awaitTimeout: 0
        clipX: 0px
        clipY: 0px
        clipWidth: 200px
        clipHeight: 100px
        fullPage: false
        omitBackground: true
        type: jpeg
        quality: 75
