/* Achtung: Hier Verweis auf richtiges Libref setzen */
libname data "C:\DATEN\QUELLEN";

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=MOVING_AVERAGE_3
	SPECLABEL="Moving Average (Smoothing window=3)"
	SPECTYPE=MOVEAVG
	SPECSOURCE=FSUI
;
	FORECAST TRANSFORM = NONE
		NOINT  
		P = ( 1 2 3 )
		AR = ( 0.3333333333333333 0.3333333333333333 0.3333333333333333 );
	ESTIMATE NOEST NOSTABLE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=MOVING_AVERAGE_4 SPECLABEL="Moving Average (Smoothing window=4)"
	SPECTYPE=MOVEAVG
	SPECSOURCE=FSUI
;
	FORECAST TRANSFORM = NONE
		NOINT  
		P = ( 1 2 3 4)
		AR = ( 0.25 0.25 0.25 0.25);
	ESTIMATE NOEST NOSTABLE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=MOVING_AVERAGE_5
	SPECLABEL="Moving Average (Smoothing window=5)"
	SPECTYPE=MOVEAVG
	SPECSOURCE=FSUI
;
	FORECAST TRANSFORM = NONE
		NOINT  
		P = ( 1 2 3 4 5)
		AR = ( 0.2 0.2 0.2 0.2 0.2);
	ESTIMATE NOEST NOSTABLE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=MOVING_AVERAGE_6
	SPECLABEL="Moving Average (smoothing window=6)"
	SPECTYPE=MOVEAVG

;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT  
		P = ( 1 2 3 4 5 6 )
		AR = ( 0.16666666666666666 0.16666666666666666 0.16666666666666666 0.16666666666666666 0.16666666666666666 0.16666666666666666 );
	ESTIMATE NOEST NOSTABLE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=RANDOMWALK
	SPECLABEL="Random Walk"
	SPECTYPE=RANDWALK

;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT 
		DIF = ( 1 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=RANDOMWALKSEASONAL
	SPECLABEL="Random Walk (Seasonal)"
	SPECTYPE=RANDWALK

;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT 
		DIF = ( 1 s );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=AVERAGE
	SPECLABEL="Mean"
	SPECTYPE=ARIMA
;
	FORECAST SYMBOL = Y TRANSFORM = NONE;
	ESTIMATE 
		METHOD=ML 
		CONVERGE=1.0E-4 
		MAXITER=150 
		DELTA=1.0E-4 
		SINGULAR=1.0E-7;
run;

proc hpfesmspec repository=data.MEINEMODELLE
	name=SIMPLE
	label="Simple Exponential Smoothing";
	esm method=simple;
run;

proc hpfesmspec repository=data.MEINEMODELLE
	name=DOUBLE
	label="Double Exponential Smoothing";
	esm method=double;
run;

proc hpfesmspec repository=data.MEINEMODELLE
	name=LINEAR
	label="Linear Exponential Smoothing";
	esm method=linear;
run;

proc hpfesmspec repository=data.MEINEMODELLE
	name=DAMPED_TREND
	label="Damp-Trend Exponential Smoothing";
	esm method=damptrend;
run;

proc hpfesmspec repository=data.MEINEMODELLE
	name=SEASONAL
	label="Seasonal Exponential Smoothing";
	esm method=addseasonal;
run;

proc hpfesmspec repository=data.MEINEMODELLE
	name=WINTERS
	label="Winters Method";
	esm method=winters;
run;

proc hpfesmspec repository=data.MEINEMODELLE
	name=ADDITIVE_WINTERS
	label="Additive-Winters Method";
	esm method=addwinters;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=CURVEFIT_LINEAR
	SPECLABEL="Trend Curve (linear)"
	SPECTYPE=CURVEFIT
;
	FORECAST TRANSFORM = NONE;
	INPUT PREDEFINED = LINEAR
		TRANSFORM = NONE;
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_001
	SPECLABEL="ARIMA (0,0,1)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST TRANSFORM = NONE 
		Q = ( 1 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_002
	SPECLABEL="ARIMA (0,0,2)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST TRANSFORM = NONE 
		Q = ( 1 2 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_012
	SPECLABEL="ARIMA (0,1,2)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST TRANSFORM = NONE
		NOINT 
		DIF = ( 1 ) 
		Q = ( 1 2 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_100
	SPECLABEL="ARIMA (1,0,0)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST TRANSFORM = NONE 
		P = ( 1 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_200
	SPECLABEL="ARIMA (2,0,0)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST TRANSFORM = NONE 
		P = ( 1 2 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_110
	SPECLABEL="ARIMA (1,1,0)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST TRANSFORM = NONE
		NOINT 
		DIF = ( 1 ) 
		P = ( 1 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_210
	SPECLABEL="ARIMA (2,1,0)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST TRANSFORM = NONE
		NOINT 
		DIF = ( 1 ) 
		P = ( 1 2 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_111
	SPECLABEL="ARIMA (1,1,1)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT 
		DIF = ( 1 ) 
		P = ( 1 )
		Q = ( 1 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_112
	SPECLABEL="ARIMA (1,1,2)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT 
		DIF = ( 1 ) 
		P = ( 1 )
		Q = ( 1 2 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_211
	SPECLABEL="ARIMA (2,1,1)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT 
		DIF = ( 1 ) 
		P = ( 1 2 )
		Q = ( 1 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_101
	SPECLABEL="ARIMA (1,0,1)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT  
		P = ( 1 )
		Q = ( 1 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_102
	SPECLABEL="ARIMA (1,0,2)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT  
		P = ( 1 )
		Q = ( 1 2 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_201
	SPECLABEL="ARIMA (2,0,1)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT  
		P = ( 1 2 )
		Q = ( 1 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.MEINEMODELLE
	SPECNAME=ARIMA_202
	SPECLABEL="ARIMA (2,0,2)"
	SPECTYPE=ARIMA
	SPECSOURCE=FSUI
;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT  
		P = ( 1 2 )
		Q = ( 1 2 );
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	/* Generated at: Mar 6, 2013 10:36:23 AM
	* Model: MULTIREG
	* Label: Y =   CONST  + CUM_PROFILE
	*/
	MODELREPOSITORY = data.MEINDEMODELLE
		SPECNAME=PROFIL_REGRESSION
		SPECLABEL="Profil-Regression"
		SPECTYPE=MULTIREG
		SPECSOURCE=FSUI
	;
	FORECAST SYMBOL = Y TRANSFORM = NONE;
	INPUT SYMBOL = CUM_PROFILE
		TRANSFORM = NONE;
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFARIMASPEC
	MODELREPOSITORY = data.meinemodelle
	SPECNAME=SUBSETARIMA
	SPECLABEL="Subset-ARIMA (mit Input)"
	SPECTYPE=SUBSETARIMA
	SPECSOURCE=FSUI
;
	FORECAST SYMBOL = Y TRANSFORM = NONE
		NOINT  
		P = ( 1 )
		Q = ( 1 );
	INPUT SYMBOL = cum_profile
		TRANSFORM = NONE;
	ESTIMATE 
		METHOD=CLS 
		CONVERGE=0.0010 
		MAXITER=50 
		DELTA=0.0010 
		SINGULAR=1.0E-7;
run;

Proc HPFSELECT
	MODELREPOSITORY = data.MEINEMODELLE
	SELECTNAME=BENUTZERDEFINIERT
	SELECTLABEL="Benutzerdefinierte Modellliste"
;
	SELECT
		HOLDOUT=0
		HOLDOUTPCT=100.0
		CRITERION=MAE;

	* SPEC RANDOMWALK;
	SPEC RANDOMWALKSEASONAL;

	* SPEC AVERAGE;
	* SPEC MOVING_AVERAGE_6;
	* SPEC MOVING_AVERAGE_5;
	* SPEC MOVING_AVERAGE_4;
	* SPEC MOVING_AVERAGE_3;
	SPEC PROFIL_REGRESSION;
	SPEC SUBSETARIMA;

	/* SPEC SIMPLE;
	SPEC DOUBLE;
	SPEC LINEAR;
	SPEC DAMPED_TREND;
	   SPEC SEASONAL;
	SPEC WINTERS;
	SPEC ADDITIVE_WINTERS;
	SPEC ARIMA_001;
	SPEC ARIMA_002;
	SPEC ARIMA_011;
	SPEC ARIMA_012;
	SPEC ARIMA_100;
	SPEC ARIMA_200;
	SPEC ARIMA_110;
	SPEC ARIMA_210;
	SPEC ARIMA_111;
	SPEC ARIMA_211;
	SPEC ARIMA_112;
	SPEC ARIMA_101;
	SPEC ARIMA_201;
	SPEC ARIMA_102;
	SPEC ARIMA_202;*/
run;