/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Dienstag, 20. März 2018 at 10:38:14
   By task:     Import Data Wizard
   
   Source file:
   C:\Users\germsz\Desktop\Partnertag\wineDemand_attributes.csv
   Server:      Local File System
   
   Output data: DATA.wineDemand_attributes
   Server:      SASApp
   
   Note: In preparation for running the following code, the Import
   Data wizard has used internal routines to transfer the source data
   file from the local file system to SASApp. There is no SAS code
   available to represent this action.
   -------------------------------------------------------------------- */
libname winedemo "/opt/data/wine";

DATA winedemo.wineDemand_attributes;
    LENGTH
        PRODUCT_ID       $ 20
        STORE_LOCATION_ID $ 14
        Reseller_ID      $ 24
        alcohol_c        $ 13
        citric_acid_c    $ 13
        chlorides_c      $ 13
        fixed_acidity_c  $ 13
        volatile_acidity_c $ 13
        residual_sugar_c $ 13
        free_sulfur_dioxide_c $ 13
        total_sulfur_dioxide_c $ 13
        pH_c             $ 13
        sulphates_c      $ 13
        quality            8
        Sentiment        $ 8 ;
    FORMAT
        PRODUCT_ID       $CHAR20.
        STORE_LOCATION_ID $CHAR14.
        Reseller_ID      $CHAR24.
        alcohol_c        $CHAR13.
        citric_acid_c    $CHAR13.
        chlorides_c      $CHAR13.
        fixed_acidity_c  $CHAR13.
        volatile_acidity_c $CHAR13.
        residual_sugar_c $CHAR13.
        free_sulfur_dioxide_c $CHAR13.
        total_sulfur_dioxide_c $CHAR13.
        pH_c             $CHAR13.
        sulphates_c      $CHAR13.
        quality          BEST1.
        Sentiment        $CHAR8. ;
    INFORMAT
        PRODUCT_ID       $CHAR20.
        STORE_LOCATION_ID $CHAR14.
        Reseller_ID      $CHAR24.
        alcohol_c        $CHAR13.
        citric_acid_c    $CHAR13.
        chlorides_c      $CHAR13.
        fixed_acidity_c  $CHAR13.
        volatile_acidity_c $CHAR13.
        residual_sugar_c $CHAR13.
        free_sulfur_dioxide_c $CHAR13.
        total_sulfur_dioxide_c $CHAR13.
        pH_c             $CHAR13.
        sulphates_c      $CHAR13.
        quality          BEST1.
        Sentiment        $CHAR8. ;
    INFILE '/opt/data/raw/wineDemand_attributes.csv'
        LRECL=199
        ENCODING="UTF-8"
        TERMSTR=CRLF
        DLM=','
        MISSOVER
        DSD
        firstobs=2;
    INPUT
        PRODUCT_ID       : $CHAR20.
        STORE_LOCATION_ID : $CHAR14.
        Reseller_ID      : $CHAR24.
        alcohol_c        : $CHAR13.
        citric_acid_c    : $CHAR13.
        chlorides_c      : $CHAR13.
        fixed_acidity_c  : $CHAR13.
        volatile_acidity_c : $CHAR13.
        residual_sugar_c : $CHAR13.
        free_sulfur_dioxide_c : $CHAR13.
        total_sulfur_dioxide_c : $CHAR13.
        pH_c             : $CHAR13.
        sulphates_c      : $CHAR13.
        quality          : ?? BEST1.
        Sentiment        : $CHAR8. ;
RUN;
