*  Begin EG generated code (do not edit this line);
*
*  Stored process registered by
*  Enterprise Guide Stored Process Manager V7.1
*
*  ====================================================================
*  Stored process name: CapabilityPlot
*  ====================================================================
*;


*ProcessBody;

%STPBEGIN;

%LET _SASSERVERNAME=%NRBQUOTE(SASApp);

*  End EG generated code (do not edit this line);


*%let lsl=70;
*%let table=abt_tablet_production;

ods graphics on;

/* -------------------------------------------------------------------
   PROC SHEWHART does not support DEVICE=ACTIVEX. Switching to PNG.
   ------------------------------------------------------------------- */
OPTIONS DEV=PNG;

TITLE;
TITLE1 "Capability analysis of: Dissolution";
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";

ODS EXCLUDE EXTREMEOBS MODES MOMENTS QUANTILES;

PROC CAPABILITY DATA=libva.&table.
	CIBASIC(TYPE=TWOSIDED ALPHA=0.05)
	MU0=0;
	VAR Dissolution;
	SPEC LSL=	&lsl. 	WLSL=2 	LLSL=2 	CLSL=BLACK 	CLEFT=YELLOW;
	HISTOGRAM  Dissolution / NORMAL	( 	W=1 	L=1 	COLOR=YELLOW  MU=EST SIGMA=EST)

		CAXIS=PURPLE
		CTEXT=BLACK
		CFRAME=WHITE
		CBARLINE=BLACK
		CFILL=GRAY
	;
	INSET
		MEAN var
		/ POSITION=NW
		CTEXT=BLUE
		CFILL=CXD3D3D3
		CFRAME=BLACK
		CHEADER=BLACK
		HEIGHT=2
	;
RUN;
TITLE; FOOTNOTE;
/* -------------------------------------------------------------------
   Restoring original device type setting.
   ------------------------------------------------------------------- */
OPTIONS DEV=ACTIVEX;

*  Begin EG generated code (do not edit this line);
;*';*";*/;quit;
%STPEND;

*  End EG generated code (do not edit this line);

